

<!DOCTYPE html> 














<html>
<head>
<meta content="text/html; charset=UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1">


<meta name="keywords" content="">



<meta name="description" content="">





<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

 
 












  






 
	 
	
	
		
	
	
	
	
	<link id="favicon" rel="shortcut icon" type="image/png"/>
	




<link href="css/onlineApplicationForm/custommenu.css" rel="stylesheet">
<link href="css/onlineApplicationForm/tab.css" rel="stylesheet">

<link rel="stylesheet" type="text/css" href="css/onlineApplicationForm/jquery.tabs-ie.css?v=19" />

<link rel="stylesheet" type="text/css" href="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.11/themes/redmond/jquery-ui.css?v=19" />

<link rel="stylesheet" type="text/css" href="css/onlineApplicationForm/ui.jqgrid.css?v=19" />

<link rel="stylesheet" type="text/css" href="css/onlineApplicationForm/layout.css?v=19" />

<link rel="stylesheet" type="text/css" href="css/onlineApplicationForm/admin/styleForLX.css?v=19" />

<link rel="stylesheet" type="text/css" href="css/onlineApplicationForm/jquery-ui_LX.min.css?v=19" />

<link rel="stylesheet" type="text/css" href="css/onlineApplicationForm/admin/styleForOA.css?v=19" />

<link rel="stylesheet" type="text/css" href="css/onlineApplicationForm/jquery.mCustomScrollbar.css?v=19" />

<link rel="stylesheet" type="text/css" href="css/onlineApplicationForm/easy-responsive-tabs.css?v=19" />

<link rel="stylesheet" type="text/css" href="css/font-awesome.min.css?v=19" />

<link rel="stylesheet" type="text/css" href="css/onlineApplicationForm/bootstrap.css?v=19" />

<link rel="stylesheet" type="text/css" href="css/onlineApplicationForm/bootstrap-select.min.css?v=19" />

<link rel="stylesheet" type="text/css" href="css/onlineApplicationForm/icons.css?v=19" />

<link rel="stylesheet" type="text/css" href="css/onlineApplicationForm/notify.css?v=19" />

<link rel="stylesheet" type="text/css" href="css/onlineApplicationForm/form76621/main.css?v=19" />

<link rel="stylesheet" type="text/css" href="css/onlineApplicationForm/form76621/main.css?v=19" />





 <script type="text/javascript" src="js/onlineAppForm/jquery.min.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/jquery-1.11.1.min.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/bootstrap.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/bootstrap-select.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/bootstrap-responsive-tabs.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/main_dashborad.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/jquery-migrate-1.2.1.min.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/jquery.dataTables.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/jquery.tabs.pack.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/jquery.datePicker.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/jquery.jqGrid.min.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/grid.locale-en.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/validation.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/checkboxselect.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/jquery.alerts.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/formViewMaster.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/formViewTabsMaster.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/jquery.mCustomScrollbar.concat.min.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/searchSlots.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/pagination.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/formMaster.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/form76621.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/GCBgenericMethods.js?v=19"></script>
 
 <script type="text/javascript" src="js/onlineAppForm/GCBValidationMethods.js?v=19"></script>
 



<!--<script src="js/main.js"></script>-->
<script type="text/javascript">
var layout_identifier="";

$(function(){
$('.selectpicker').selectpicker();
})
</script>
<script type="text/javascript">
	 	var viewArray = new Array();
</script>






<style>
#container-11{
	border:1px solid rgb(35, 180, 236);
/* 	border-left:1px solid rgb(35, 180, 236); */
/* 	border-right:1px solid rgb(35, 180, 236); */
}
</style>


<style>
#container {
            width: 968px;
            margin: 0 auto;
        }
		
@media only screen and (max-width: 768px) {
    #container {
        width: 90%;
        margin: 0 auto;
    }
}
.curentli{ display:block !important}
.oldli{ display:none !important}
.overlayBG {
	background-color: #000000;
	opacity: 0.6;
	filter: alpha(opacity = 70);
	height: 100%;
	left: 0;
	position: fixed;
	top: 0;
	width: 100%;
	z-index: 0;
}

.ui-jqgrid-htable,.ui-jqgrid-btable {
	width: 100% !important
}

.popup_div {
	z-index: 2;
	position: fixed;
	top:10px;
}

.portlet_topper {
	height: 24px;
	background: url(../EForms/images/onlineAppForm/bg_portlet_top.gif)
		repeat-x top left;
	padding: 0px 5px 0px 10px;
	cursor: move;
}

.popupheader {
	display: inline;
	font-size: 10pt;
	color: #fff;
	font-weight: bold;
	float: left;
	font-family: Tahoma, Geneva, sans-serif;
	line-height: 24px;
	float: left;
}

.popupfilesheader {
	height: 33px;
	line-height: 33px;
	background: url(../EForms/images/onlineAppForm/bg_popupfilesheader.gif)
		repeat-x top left;
	padding-left: 10px;
	font-size: 11px;
	font-family: Tahoma, Geneva, sans-serif;
}

.arrowplace {
	float: right;
	font-size: 11px !important;
	line-height: 24px;
	color: #fff;
}

.arrowplace a {
	color: #fff;
	text-decoration: none;
	padding-right: 15px;
	background: url(../EForms/images/onlineAppForm/ico_close2.gif) no-repeat
		right 7px;
	display: block;
}

.arrowplace a:hover {
	color: #fff;
	text-decoration: underline;
}

.popup_content { /*padding:7px 20px 10px 20px;*/
	background: #d6e3e9 url(../EForms/images/onlineAppForm/popupbg.gif)
		repeat-x top left;
	font-family: Tahoma, Geneva, sans-serif;
}

.popup_button_area {
	background: #d6e3e9;
	padding: 10px;
}

.butonhldr_popup {
	background: none repeat scroll 0 0 #D8E3E9;
}
.b_g_c_white {
	background-color: #ffffff !important;
}

.dwnld {
	background: none repeat scroll 0 0 #3B7CBE !important;
	border-radius: 3px 3px 3px 3px;
	color: #FFFFFF !important;
	font-size: 11px !important;
	padding: 2px 4px;
	text-align: center;
	text-decoration: none !important;
	width: 60px;
}

#backgroundPopup {
	display: none;
	position: fixed;
	_position: absolute; /* hack for internet explorer 6*/
	height: 100%;
	width: 100%;
	top: 0;
	left: 0;
	background: #000000;
	border: 1px solid #cecece;
	z-index: 1;
}

#popupContact {
	display: none;
	position: fixed;
	_position: absolute; /* hack for internet explorer 6*/
	width: 400px;
	background: #FFFFFF;
	border: 1px solid #97A5B0;
	z-index: 2;
	padding: 12px;
	font-size: 13px;
}

#popupContact h1 {
	text-align: left;
	color: #6FA5FD;
	font-size: 22px;
	font-weight: 700;
	border-bottom: 1px dotted #D3D3D3;
	padding-bottom: 2px;
	margin-bottom: 20px;
}

#popupContactClose {
	font-size: 14px;
	line-height: 14px;
	right: 6px;
	top: 4px;
	position: absolute;
	color: #6fa5fd;
	font-weight: 700;
	display: block;
}

#popupChangePassword {
	display: none;
	position: fixed;
	_position: absolute; /* hack for internet explorer 6*/
	width: 400px;
	background: #FFFFFF;
	border: 1px solid #97A5B0;
	z-index: 2;
	padding: 12px;
	font-size: 13px;
}

#popupChangePasswordClose {
	font-size: 14px;
	line-height: 14px;
	right: 6px;
	top: 4px;
	position: absolute;
	color: #6fa5fd;
	font-weight: 700;
	display: block;
}

.viewListIcon:hover {
	background: url(images/onlineAppForm/View_Hover.png)
}

.tablelist2 {
	background-color: #f9fbfb;
	font: 11px "Tahoma", Arial, Helvetica, sans-serif;
}

.iconClass {
	border-right: solid 1px #809bae;
	border-bottom: solid 1px #809BAE;
	margin: 0px;
	white-space: nowrap;
	text-indent: 5px;
	padding-right: 5px;
	width: 60px;
}

.tablelist2 th {
	background: url(images/onlineAppForm/thbg2.gif) repeat-x top left;
	cursor: pointer;
	height: 22px;
	font-size: 11px;
	color: #000;
	line-height: 22px;
	text-align: left;
	border-right: solid 1px #809bae;
	border-bottom: solid 1px #809bae;
	border-top: solid 1px #809bae;
	margin: 0px;
	white-space: nowrap;
	padding: 0 25px 0 25px;
}

.tablelist2 th.checkbox {
	background: url(images/onlineAppForm/thbg2.gif) repeat-x top left;
	cursor: pointer;
	height: 22px;
	font-size: 11px;
	color: #000;
	line-height: 22px;
	text-indent: 5px;
	text-align: left;
	padding-right: 5px;
	border-right: solid 1px #809bae;
	border-bottom: solid 1px #809bae;
	margin: 0px;
	white-space: nowrap;
}

.tablelist2 td {
	font-size: 11px;
	color: #000;
	font-weight: normal;
	line-height: 24px !important;
	border-bottom: solid 1px #809bae;
	margin: 0px;
	white-space: normal;
	text-indent: 10px;
}

.tablelist2 td.pagination td {
	font-size: 11px;
	color: #000;
	font-weight: normal;
	background: url(images/thbg2.gif) repeat-x bottom left;
	border-bottom: 0px !important;
	margin: 0px;
	padding: 0px 10px !important;
	white-space: normal;
	line-height: 24px;
	text-indent: 0px;
}

.formContent .btnContainer {
	margin: 10px 0 30px;
	text-align: center;
}

.formContent {
	background-color: #F3FDFE;
	border: 1px solid #A4B9BE;
	margin: 10px 0px;
}

table.formTable {
	margin: 15px auto 0;
	padding-top: 10px;
}

table.formTable td {
	color: #415E70;
	padding: 14px 0;
}

.normalinput {
	border: 1px solid #7F9EBD;
	height: auto;
	width: 100%;
}

.clear-float {
	margin: 0;
	padding: 0;
	clear: both;
}

.info_header_grid {
	border-bottom: 1px solid #41677A;
	font-size: 12pt;
	font-weight: bold;
	line-height: 28px;
	margin: 5px 0;
	padding-left: 0;
}

a.generatebuttn_grid {
	background: url("/EForms/images/onlineAppForm/butt_generate_rght.gif")
		no-repeat scroll right top rgba(0, 0, 0, 0);
	color: #000000;
	display: block;
	float: left;
	font-family: Arial, Helvetica, sans-serif;
	font-size: 11px;
	font-weight: bold;
	height: 22px;
	line-height: 22px;
	margin-right: 4px;
	margin-top: 0;
	padding-right: 10px;
	text-decoration: none;
}

a.generatebuttn_grid span {
	background: url("/EForms/images/onlineAppForm/butt_generate.gif")
		no-repeat scroll 0 0 rgba(0, 0, 0, 0);
	display: block;
	line-height: 22px;
	margin-right: 0;
	padding: 0 0 0 10px;
}

a.generatebuttn_grid:hover span {
	text-decoration: none;
	color: rgb(6, 131, 199);
}

<!--
added by bindiya -->.imageHover {
	
}

.imageHover:hover {
	height: 100px;
	width: 100px;
	z-index: 500;
	margin-left: -5%;
	margin-top: -3%;
	position: absolute;
	border: 3px outset #1192CE;
}

.tableHeadingWhiteSpaceNowrap{
white-space: nowrap;
}

</style>
<script type="text/javascript">
	var cp = 0;
    var cn = 0;
	var cup = 0;
    var cdwn = 0;
   
    
    $(document).ready(function() {
    	$('.upTab').on('click', function(){
    		
    		if(cup == 0)
    		{
    			$('#parentVerticalTab ul').animate({'top': "0"});	
    		}
    		else if(cup <= $('#parentVerticalTab ul li').length -1 && cup > 0)
    		{

    			$('#parentVerticalTab ul').css({'top': "+=122"});
    			$('#parentVerticalTab ul li.curentli').removeClass('resp-tab-active');
    			$('#parentVerticalTab ul li.curentli').removeAttr('style');
    			$('#parentVerticalTab ul li.curentli').first().removeClass('curentli').addClass('oldli');

    			$('#parentVerticalTab ul li.curentli').first().prev().removeClass('oldli').addClass('curentli  resp-tab-active');
    			$('#parentVerticalTab ul li.curentli').last().removeClass('curentli').addClass('oldli');
    			$('#parentVerticalTab ul li.curentli:nth-child('+cup+')').trigger('click');
    			$('#parentVerticalTab ul li.curentli:nth-child('+cup+')').next().removeAttr('style');
    			cup--;
    			cdwn--;
    		}
    	});			

    	$('.downTab').on('click', function(){
    		if(cdwn <= $('#parentVerticalTab ul li').length - 1)
    		{
    			
    			$('#parentVerticalTab ul').css({'top': '-=122'});
    			$('#parentVerticalTab ul li.curentli').removeClass('resp-tab-active');
    			$('#parentVerticalTab ul li.curentli').removeAttr('style');
    			$('#parentVerticalTab ul li.curentli').last().next().removeClass('oldli').addClass('curentli  resp-tab-active');
    			$('#parentVerticalTab ul li.curentli').last().removeAttr('style');
    			$('#parentVerticalTab ul li.curentli:nth-child('+cdwn+')').next().trigger('click');
    			cdwn++;
    			cup++;
    		}
    	});
    	var tabLayout = 'horizontalWithIcon';
    	getTabs(tabLayout);
	$('.prevTab').on('click', function(){
			if(cp == 0)
			{
				$('#parentHorizontalTab ul').animate({left: "0"});	
			}
			else if(cp <= $('#parentHorizontalTab ul li').length -1 && cp > 0)
			{
				$('#parentHorizontalTab ul').animate({left: "+=105"});
				$('#parentHorizontalTab ul li.curentli').removeClass('resp-tab-active');
				$('#parentHorizontalTab ul li.curentli').removeAttr('style');
				$('#parentHorizontalTab ul li.curentli:nth-child('+cp+')').trigger('click');
				$('#parentHorizontalTab ul li.curentli:nth-child('+cp+')').next().removeAttr('style');
				
				$('#parentHorizontalTab ul li.curentli').last().removeClass('curentli').addClass('oldli');
				cp--;
				cn--;
			}
	});
	$('.nextTab').on('click', function(){
			if(cn <= $('#parentHorizontalTab ul li').length - 1)
			{
				$('#parentHorizontalTab ul').animate({left: "-=105", width: '+=15%'});
				$('#parentHorizontalTab ul li.curentli').removeClass('resp-tab-active');
				$('#parentHorizontalTab ul li.curentli').removeAttr('style');
				$('#parentHorizontalTab ul li.curentli').last().removeAttr('style');
				$('#parentHorizontalTab ul li.curentli').last().next().trigger('click');
				$('#parentHorizontalTab ul li.curentli').last().next().removeClass('oldli').addClass('curentli  resp-tab-active');
				cn++;
				cp++;
			}
	});
	

		
	$( ".btn_oa a" ).click(function(event) {
	//console.log(2);
		event.stopImmediatePropagation(); 


	});
		
		
			 
			//LOADING POPUP
			//Click the button event!
		
						
			//CLOSING POPUP
			//Click the x event!
			$("#popupContactClose").click(function(){
				disablePopup();
			});
			//Click out event!
			$("#backgroundPopup").click(function(){
				disablePopup();
			});
			//Press Escape event!
			$(document).keypress(function(e){
				if(e.keyCode==27 && popupStatus==1){
					disablePopup();
				}
			});
			$("#popupChangePasswordClose").click(function(){
				disablePopupChngPwd();
			});
			$("#backgroundPopup").click(function(){
				disablePopupChngPwd();
			});
				
			 
 });

var var1= 'BEd 2K22 Preference Application Form';
document.title = "BEd 2K22 Preference Application Form";

	
	
	var pgNo = 1;
	  var totalPages="";
          var pageStart="";
          var totalPagesForPaging ="";
          var totalAllowedPages ="";
          var nextID ="";
          var previousID = "";
          var isNext ="";
          var isPrevious = "";
          var recordCount = "";
          var pageLimit = "";
	
	
	
		  //setTimeout("preventBack()", 0);
	
		  window.onunload=function(){null};
	
			
			function fnAdminView(){
			
				
				document.getElementById('officeUseField').style.display='none';
				document.getElementById('CandUseField').style.display='block';
				
			
			}
	

	var isCustomizedGridRequired="",isNewWindowOnCreate="",isDownloadUploadRequired="",isDeleteRequired="",isAutoCloseWindow="",isNewListingTab="",isSameFormOnSubmit="",isNewFormOnSubmit="",NewListingTab="",NewFormOnSubmit="",isPdfexproUploadRequired="",isUploadRequired="",maxListingRows="";
	


		
		/*online assessment tab code ends*/
	
	/*functions for online assessment tab ends*/
	function populateTabs(pdfTabList){
		
		var constantVar=1;
		if('horizontalWithIcon'=='custom' && typeof window.populateCustomizedTabs == 'function') {
			$.when(populateCustomizedTabs(pdfTabList)).then(setCustomTabValues(pdfTabList));
	    }else{
	    	//console.log(1);
		var noOfPdfTabList=pdfTabList.length;
		var tabName = "",tabId="",createAllowed="",iconPath="",enablePB="";
		var arrCount=0;
		 var arr=new Array();
		 var tabLayout='horizontalWithIcon';
		for(var i=0;i< noOfPdfTabList;i++){
		var notAnEmptyTab = false;
		if('horizontalWithIcon'=='horizontalWithIcon' || 'horizontalWithIcon'=='horizontalWithoutIcon'){
			  lastFragment = $('#tabs li > a:last-child').attr("id");
			}
		else if('horizontalWithIcon'=='verticalWithIcon' || 'horizontalWithIcon'=='verticalWithoutIcon'){
			  lastFragment = $('#tabs li > a:last-child').attr("id");
			}
		else{
				lastFragment = $('#tabs li > a:last-child').attr("href");
			}
			  if(lastFragment!=undefined){
			  lastFragment = lastFragment.substring(1,lastFragment.length);
			  lastFragmentId = lastFragment.substring(9,lastFragment.length);
			  var tabCount = $('#tabs li').length;
			  var fragmentCount=parseInt(lastFragmentId) + parseInt(tabCount);
			  tabName = pdfTabList[i].getAttribute("tabname");
			  tabType = pdfTabList[i].getAttribute("tabType");
			  tabDesc = pdfTabList[i].getAttribute("tabDesc");
			  tabId = pdfTabList[i].getAttribute("tabId");
			  iconPath = pdfTabList[i].getAttribute("iconPath");
			  subsOnClick = pdfTabList[i].getAttribute("subsOnClick");
			  serviceID = pdfTabList[i].getAttribute("serviceID");
			  if(tabType!=null && tabType.toLowerCase()=="listing"){
			   tabListForm = pdfTabList[i].getAttribute("tabListFormId");
			   listFormId = pdfTabList[i].getAttribute("listFormId");
			   createAllowed = pdfTabList[i].getAttribute("createAllowed");
			   isNewWindowOnCreate = pdfTabList[i].getAttribute("isNewWindowOnCreate");
			   isCustomizedGridRequired = pdfTabList[i].getAttribute("isCustomizedGridRequired");
			   isDownloadUploadRequired =pdfTabList[i].getAttribute("isDownloadUploadRequired");
			   isUploadRequired =pdfTabList[i].getAttribute("isUploadRequired");	
			   isAutoCloseWindow =pdfTabList[i].getAttribute("isAutoCloseWindow");
			   isDeleteRequired =pdfTabList[i].getAttribute("isDeleteRequired");
			   isNewListingTab =pdfTabList[i].getAttribute("isNewListingTab");
			   isSameFormOnSubmit =pdfTabList[i].getAttribute("isSameFormOnSubmit");
			   isNewFormOnSubmit = pdfTabList[i].getAttribute("isNewFormOnSubmit");
			   NewListingTab = pdfTabList[i].getAttribute("NewListingTab");
			   NewFormOnSubmit = pdfTabList[i].getAttribute("NewFormOnSubmit");
			   isPdfexproUploadRequired=pdfTabList[i].getAttribute("isPdfexproUploadRequired");
			   maxListingRows=pdfTabList[i].getAttribute("max_listing_rows");

			  }


			 
			  var pdfList = pdfTabList[i].getElementsByTagName("PDF");
				
				if(pdfList.length>0 || (tabType!=null && tabType.toLowerCase() == "listing" && tabListForm != "")){
					$('body').addClass('eform-wrp');
					
					var linkRef=$('#tabs li:last a').attr('href');
					var functionOnClick=$('#tabs li:last a').attr('onclick');
				if(tabType ==("Hall Ticket") || tabType == ("Slot booking") || tabType == ("Evaluation") || tabType ==("Question Paper Publish")){
					if(linkRef.indexOf("#")>-1){
						linkRef = linkRef.substring(1,linkRef.length);
					}
					functionOnClick="displayFWCodedTabs('fragment-"+fragmentCount+"')";
				}
					
										
					
					
					newTab = "<li><a href='#fragment-"+fragmentCount+"' ";
					if(tabType!= undefined && tabType.toLowerCase() == "listing")
						newTab = newTab + "onclick=\"fnGetChildDataForList('"+tabListForm+"','"+fragmentCount+"','listGrid"+fragmentCount+"','"+tabId+"','','"+listFormId+"')\"";
					else
						{
						newTab = newTab+"onclick = \""+functionOnClick+"\"";
						}
						
						
					newTab = newTab + " ><span id='"+tabId+"_Tab_Name' title = \""+tabName+"\">"+ tabName+"</span></a></li>";
					$('#tabs').append(newTab);
						
						notAnEmptyTab =true;
					  var newDiv = "<div ";
					  if(tabType!=null && tabType.toLowerCase() == "listing"){
							 
									newDiv = newDiv + "style='padding:0px 35px;position:relative;' class='tabs-container tabs-hide container-fluid '";
							  }else{
							   newDiv = newDiv + "style='padding:0px 15px;position:relative;' class='tabs-container tabs-hide '"; 
							  }
					  
					  newDiv = newDiv + " id='fragment-"+fragmentCount+"' ><div class=\"desc\"> <div class=\"clear\"></div><div class=\"informantion-summary\">";
					  if(tabType!=null && tabType.toLowerCase() != "listing"){
						  if(tabType == "PDF/HTML"){
							  newDiv = newDiv +"<div class=\"desc-heading col-md-10 col-sm-12 col-xs-12\" style=\"overflow: hidden;\" ><span id='"+tabId+"_Tab_Description'>"+tabDesc+"</span></div> <div id='print"+fragmentCount+"' style=\"overflow: hidden; display:none\" class=\"desc-heading col-md-2 col-sm-12 col-xs-12\"><a onclick=\"printTab('fragment-"+fragmentCount+"');\" href=\"#nogo\" style=\"visibility: visible;\"><div class=\"btn btn-default emailprint\"> <span><i class=\"fa fa-print\"></i> Print Tab</span></div></a></div> </div><div class=\"clear\"></div></div><table width='100%' cellspacing='0' cellpadding='0' border='0'";
						  }
						  else
							  { 
						newDiv = newDiv +"<div class=\"desc-heading\"> <span id='"+tabId+"_Tab_Description'>"+tabDesc+"</span></div></div><div class=\"clear\"></div></div><table width='100%' cellspacing='0' cellpadding='0' border='0'";}
						newDiv = newDiv + "style='background-color: #eaf4f9;padding-left:0px;' class='info_table'";
						newDiv = newDiv + "id='table-"+fragmentCount+"'><tr><td style='padding-top: 40px;padding-left:0px;'>";
						
					  }
					  if(tabType!=null && tabType.toLowerCase() == "listing"){
						  newDiv = newDiv +"<div class=\"desc-heading\"><h3 class=\"margintop20 orangecolor\"><span id='"+tabId+"_Tab_Description' class=\"sansSB\">"+tabDesc+"</span></h3></div></div><div class=\"clear\"></div></div>";
						//newDiv = newDiv + "style='background-color: #eaf4f9;' class='info_table'";
						
					  }
						

					  if(tabType!=null && tabType.toLowerCase() == "listing"){//removed class=\"text-right\"
						newDiv = newDiv + "<div id='listSearchGrid-"+fragmentCount+"'></div>";
					  newDiv = newDiv +"<div class=\"panel panel-default\" id='tableaccordionsearch-"+fragmentCount+"'>";
					  newDiv = newDiv +"<div id=\"tableOne\" role=\"tab\" class=\"panel-heading tablehead clearfix\">";
					  newDiv = newDiv +"<h4 class=\"panel-title pull-left\" data-staticKey=\"Your Selection\"> Your Selection</h4>";
					  newDiv = newDiv +"<div class=\"pull-right\" id=\"mylisting_action\">";
					  
					 // newDiv = newDiv + "<div class=\"blue-bg\">";
						
					  if(isDownloadUploadRequired=="Y"){
						  //newDiv = newDiv + "<a href='#fragment-"+fragmentCount+"' class = 'green-btn' onclick=\"fnDownloadChildForm('"+listFormId+"','"+tabListForm+"','"+fragmentCount+"')\"><span class=\"multiupload-icon\">&nbsp;</span>Download</a>" --- data-placement=\"top\" data-toggle=\"tooltip\" data-original-title=\"Download\";
					  		 newDiv = newDiv + " <a class=\"btn btn-bgcolor btn-xs download-multilingual \" href=\"#\" role=\"button\" onclick=\"fnDownloadChildForm('"+listFormId+"','"+tabListForm+"','"+fragmentCount+"','N')\" title=\"Download\" style=\"color:#fff !important\"><i class=\"fa fa-download fa-2\" ></i></a>";
					  		// newDiv = newDiv + " <a class=\"btn btn-bgcolor btn-xs \" role=\"button\" title=\"Download Blank Template\" style=\"color:#fff !important\" onclick=\"fnDownloadChildForm('"+listFormId+"','"+tabListForm+"','"+fragmentCount+"','Y')\"><i class=\"fa fa-caret-down fa-2\" data-placement=\"top\" data-toggle=\"tooltip\" data-original-title=\"Upload\"></i></a>";
					  		//newDiv = newDiv + " <a class=\"btn btn-bgcolor btn-xs \" role=\"button\" title=\"Upload Filled PDF \" style=\"color:#fff !important\" onclick=\"fnUploadExpro()\"><i class=\"fa fa-file-pdf-o\" data-placement=\"top\" data-toggle=\"tooltip\" data-original-title=\"Upload\"></i></a>";
					  		//newDiv = newDiv + " <a class=\"btn btn-bgcolor btn-xs \" data-toggle=\"modal\" data-target=\"#UploadExproModal"+fragmentCount+"\" role=\"button\" title=\"Upload expro\" style=\"color:#fff !important\"><i class=\"fa fa-file-pdf-o\" data-placement=\"top\" data-toggle=\"tooltip\" data-original-title=\"Upload\"></i></a>";

					  	  }
					  
					  if(isUploadRequired=="Y"){		
						  //newDiv = newDiv + "<a href='#fragment-"+fragmentCount+"' class = 'green-btn' onclick=\"fnDownloadChildForm('"+listFormId+"','"+tabListForm+"','"+fragmentCount+"')\"><span class=\"multiupload-icon\">&nbsp;</span>Download</a>" --- data-placement=\"top\" data-toggle=\"tooltip\" data-original-title=\"Download\";		
					  		 newDiv = newDiv + " <a class=\"btn btn-bgcolor btn-xs upload-multilingual \" data-toggle=\"modal\" data-target=\"#UploadModal"+fragmentCount+"\" role=\"button\" title=\"Upload\" style=\"color:#fff !important\"><i class=\"fa fa-upload fa-2\" data-placement=\"top\" data-toggle=\"tooltip\" data-original-title=\"Upload\"></i></a>";		
					  		 newDiv = newDiv + " <a class=\"btn btn-bgcolor btn-xs blank-multilingual \" role=\"button\" title=\"Download Blank Template\" style=\"color:#fff !important\" onclick=\"fnDownloadChildForm('"+listFormId+"','"+tabListForm+"','"+fragmentCount+"','Y')\"><i class=\"fa fa-caret-down fa-2\" data-placement=\"top\" data-toggle=\"tooltip\" data-original-title=\"Upload\"></i></a>";
					  		//newDiv = newDiv + " <a class=\"btn btn-bgcolor btn-xs \" role=\"button\" title=\"Upload Filled PDF \" style=\"color:#fff !important\" onclick=\"fnUploadExpro()\"><i class=\"fa fa-file-pdf-o\" data-placement=\"top\" data-toggle=\"tooltip\" data-original-title=\"Upload\"></i></a>";							  	
					  		//newDiv = newDiv + " <a class=\"btn btn-bgcolor btn-xs \" data-toggle=\"modal\" data-target=\"#UploadExproModal"+fragmentCount+"\" role=\"button\" title=\"Upload expro\" style=\"color:#fff !important\"><i class=\"fa fa-file-pdf-o\" data-placement=\"top\" data-toggle=\"tooltip\" data-original-title=\"Upload\"></i></a>";							  		
		
					  	  }
					  
					  if(isPdfexproUploadRequired=="Y")
						  { 
						  newDiv = newDiv + " <a class=\"btn btn-bgcolor btn-xs upload-expro-multilingual \" data-toggle=\"modal\" data-target=\"#UploadExproModal"+fragmentCount+"\" role=\"button\" title=\"Upload expro\" style=\"color:#fff !important\"><i class=\"fa fa-file-pdf-o\" data-placement=\"top\" data-toggle=\"tooltip\" data-original-title=\"Upload\"></i></a>";

						  }
					  
					  	  if(createAllowed=="Y"){ 
					  	  //newDiv = newDiv + "<a href='#fragment-"+fragmentCount+"' class = 'green-btn' onclick=\"fnGetChildForm('"+listFormId+"','"+tabListForm+"','"+fragmentCount+"')\"><span class=\"create-icon\">&nbsp;</span>Create</a>";
					  	newDiv = newDiv + " <a class=\"btn btn-bgcolor btn-xs create-multilingual \"";
					  	if(tabLayout != "standard"){
					  		newDiv = newDiv + " data-toggle=\"modal\" data-target=\"#CreateModal"+fragmentCount+"\" role=\"button\"";
					  	}//data-placement=\"top\" data-toggle=\"tooltip\" data-original-title=\"Create\" 
					  	newDiv = newDiv+" id=\"createListing-"+fragmentCount+"\" onclick=\"fnGetChildForm('"+listFormId+"','"+tabListForm+"','"+fragmentCount+"','"+tabId+"');\" title=\"Create\" style=\"color:#fff !important\"><i class=\"fa fa-plus fa-2\" ></i></a>";
					  	  }
					  	
					  	//removed style=display:none in td of reload-fragment to display reload button on grid
					  	//newDiv = newDiv + "<a href='#fragment-"+fragmentCount+"'  class = 'green-btn' id='reloadGrid-"+fragmentCount+"' onclick=\"fnGetChildDataForList('"+tabListForm+"','"+fragmentCount+"','listGrid"+fragmentCount+"','"+tabId+"','refresh','"+listFormId+"')\"><span class=\"reload-icon\">&nbsp;</span>Reload </a></div>";//data-placement=\"top\" data-toggle=\"tooltip\" data-original-title=\"Refresh\"
					  	newDiv = newDiv + " <a class=\"btn btn-bgcolor btn-xs refresh-multilingual \" href=\"#nogo\" role=\"button\" onclick=\"fnGetChildDataForList('"+tabListForm+"','"+fragmentCount+"','listGrid"+fragmentCount+"','"+tabId+"','refresh','"+listFormId+"')\" id=\"reloadGrid-"+fragmentCount+"\" title=\"Refresh\" style=\"color:#fff !important\"><i class=\"fa fa-refresh\" ></i></a> </div>";
						newDiv = newDiv + "</div>";
						/*added by bindiya*/
						 var pagenoField ="";
				 pagenoField +="<input type = \"hidden\" id= \"pagenoField"+fragmentCount+"\" value = \"1\"style=\"border:1px solid #809BAD;margin:4px;\"/>";
				 var sortingFieldInput ="";
				 sortingFieldInput +="<input type = \"hidden\" id= \"sortingFieldInput"+fragmentCount+"\" style=\"border:1px solid #809BAD;margin:4px;\"/>";
				 var sortingorderInput ="";
				 sortingorderInput +="<input type = \"hidden\" id= \"sortingorderInput"+fragmentCount+"\" style=\"border:1px solid #809BAD;margin:4px;\"/>";
				 sortingorderInput += "<input type = \"hidden\" value = \""+isNewWindowOnCreate+"\" id= \"isNewWindowOnCreate"+fragmentCount+"\"/>";
				 sortingorderInput += "<input type = \"hidden\" value = \""+isCustomizedGridRequired+"\" id= \"isCustomizedGridRequired"+fragmentCount+"\"/>";
				 sortingorderInput += "<input type = \"hidden\" value = \""+isAutoCloseWindow+"\" id= \"isAutoCloseWindow"+fragmentCount+"\"/>";
				 sortingorderInput += "<input type = \"hidden\" value = \""+isDeleteRequired+"\" id= \"isDeleteRequired"+fragmentCount+"\"/>";
				 sortingorderInput += "<input type = \"hidden\" id= \"searchFilterSaved"+fragmentCount+"\"/>";
				 sortingorderInput += "<input type = \"hidden\" value = \""+isNewListingTab+"\" id= \"isNewListingTab"+fragmentCount+"\"/>";
				 sortingorderInput += "<input type = \"hidden\" value = \""+isSameFormOnSubmit+"\" id= \"isSameFormOnSubmit"+fragmentCount+"\"/>";
				 sortingorderInput += "<input type = \"hidden\" value = \""+isNewFormOnSubmit+"\" id= \"isNewFormOnSubmit"+fragmentCount+"\"/>";
				 sortingorderInput += "<input type = \"hidden\" value = \""+NewListingTab+"\" id= \"NewlistingTab"+fragmentCount+"\"/>";
				 sortingorderInput += "<input type = \"hidden\" value = \""+NewFormOnSubmit+"\" id= \"NewFormOnSubmit"+fragmentCount+"\"/>";
				 sortingorderInput += "<input type = \"hidden\" value = \""+maxListingRows+"\" id= \"maxListingRows"+fragmentCount+"\"/>";
				 
				 $('#container-11').append(pagenoField);
				 $('#container-11').append(sortingFieldInput);
				 $('#container-11').append(sortingorderInput);
				   /*added by bindiya ends*/
					  }
					  //</td></tr></table> <div>
					  newDiv = newDiv + "<input type='hidden' id='listGridPresent"+fragmentCount+"' value='N' name='listGridPresent"+fragmentCount+"'/></div></div>";
					  
					  if(isDownloadUploadRequired=="Y"){
						  //Adding code for a new modal for upload
					  		newDiv = newDiv +"<div class=\"modal fade modal_window\" id=\"UploadModal"+fragmentCount+"\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\">";
					  		newDiv = newDiv +"<div class=\"modal-dialog\" role=\"document\">";
					  		newDiv = newDiv +"<div class=\"modal-content\">";
					  		newDiv = newDiv +" <div class=\"modal-header\">";
					  		newDiv = newDiv +" <button type=\"button\" class=\"close whiteTxt\" data-dismiss=\"modal\" aria-label=\"Close\" onclick=\"refreshListingGrid('"+fragmentCount+"')\"><span aria-hidden=\"true\">&times;</span></button>";
					  		newDiv = newDiv +"   <h4 class=\"modal-title\" id=\"myModalLabel\" data-staticKey=\"File Upload\">File Upload</h4>";
					  		newDiv = newDiv +"</div>";
					  		newDiv = newDiv +" <div class=\"modal-body\">";
					  		newDiv = newDiv +" <div class=\"container-fluid\">";
					  		newDiv = newDiv +"  <div class=\"row\" >";
					  		newDiv = newDiv +"    <div class=\"form-group\">";
					  		newDiv = newDiv +"      <label for=\"exampleInputFile\" data-staticKey=\"File input\">File input</label>";
					  		//id=\"exampleInputFile\"
					  		newDiv = newDiv +"      <input type=\"file\" name='txtUploadFilePath"+fragmentCount+"' id='txtUploadFilePath"+fragmentCount+"' />";
					  		newDiv = newDiv +"      <span class=\"alert-block instructiontext\" data-staticKey=\"File Type: *.xls and *.xlsx are allowed.\">File Type: *.xls and *.xlsx are allowed.</span> </div>";
					  		newDiv = newDiv +"  </div></div></div>";
					  		newDiv = newDiv +"<div class=\"modal-footer\">";
					  		newDiv = newDiv +"<button type=\"button\" class=\"btn btn-warning\" onclick=\"fnUploadChildForm('"+listFormId+"','"+tabListForm+"','"+fragmentCount+"')\" data-staticKey=\"Upload\">Upload</button><span id='txtMsgSpan"+fragmentCount+"'></span><span id =\"uploadAlert\" data-staticKey=\"The file you have selected is not in correct file format.\" style=\"display:none\">The file you have selected is not in correct file format.</span>";
					  		newDiv = newDiv +"</div></div></div></div>";
					  	    
					 }
					  if(isPdfexproUploadRequired=="Y")
						  { 
					   newDiv = newDiv +"<div class=\"modal fade modal_window\" id=\"UploadExproModal"+fragmentCount+"\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel\">";
				  		newDiv = newDiv +"<div class=\"modal-dialog\" role=\"document\">";
				  		newDiv = newDiv +"<div class=\"modal-content\">";
				  		newDiv = newDiv +" <div class=\"modal-header\">";
				  		newDiv = newDiv +" <button type=\"button\" class=\"close whiteTxt\" data-dismiss=\"modal\" aria-label=\"Close\" onclick=\"refreshListingGrid('"+fragmentCount+"')\"><span aria-hidden=\"true\">&times;</span></button>";
				  		newDiv = newDiv +"   <h4 class=\"modal-title\" id=\"myModalLabel\" data-staticKey=\"File Upload\">File Upload</h4>";
				  		newDiv = newDiv +"</div>";
				  		newDiv = newDiv +" <form  method=\"post\" enctype=\"multipart/form-data\" id=\"formF\">";
				  		newDiv = newDiv +" <div class=\"modal-body\">";
				  		newDiv = newDiv +" <div class=\"container-fluid\">";
				  		newDiv = newDiv +"  <div class=\"row\" >";
				  		//newDiv = newDiv +"    <div class=\"form-group\">";
				  		
				  		newDiv = newDiv +"      <label for=\"exampleInputFile\" data-staticKey=\"File input\">File input</label>";
				  		//id=\"exampleInputFile\"
				  		newDiv = newDiv +"      <input type=\"file\" name='txtUploadExproFilePath"+fragmentCount+"' id='txtUploadExproFilePath"+fragmentCount+"' />";
				  		
				  		newDiv = newDiv +"      <span class=\"alert-block instructiontext\" data-staticKey=\"File Type: *.pdf is allowed.\">File Type: *.pdf is allowed.</span> </div>";
				  		newDiv = newDiv +"  </div></div>";
				  		newDiv = newDiv +"<div class=\"modal-footer\">";
				  		newDiv = newDiv +"<button type=\"button\" class=\"btn btn-warning\" onclick=\"fnUploadExpro('"+listFormId+"','"+fragmentCount+"')\" data-staticKey=\"Upload\">Upload</button><span id='txtMsgSpan"+fragmentCount+"'></span>";
				  		newDiv = newDiv +"</div></form></div></div></div>"; 
				  	    
					  }
					  
					  
				/* 	  if(!(tabLayout=="" || tabLayout==undefined || tabLayout==null || tabLayout=="standard")){
						  newDiv = newDiv+"<div class=\"modal fade modal_window\" id=\"CreateModal"+fragmentCount+"\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLabel"+fragmentCount+"\">"+
							"<div class=\"modal-dialog modal-lg\" role=\"document\" style=\"width:100%;margin: 0px auto;position: inherit;margin: 0px;\">"+
							"<div class=\"modal-content\">"+
							"<div class=\"modal-header\" style=\"padding: 5px;\">"+
							"<button type=\"button\" style=\"padding-right:5px;margin-top: -3px;\" class=\"close whiteTxt\" data-dismiss=\"modal\" onclick=\"$('html').css('overflow','auto');\" aria-label=\"Close\" id=\"closeModal"+fragmentCount+"\"><span aria-hidden=\"true\">&times;</span></button>"+
							"<h4 class=\"modal-title\" id=\"myModalLabel"+fragmentCount+"\">"+tabName+"</h4>"+
							" </div>"+
							"<div class=\"modal-body\" id=\"listingFrameBody"+tabId+"\" style=\"padding: 0px;padding-left: 0px; padding-right: 0px;\">"+
							"<iframe src=\"\" id=\"listingFrame"+fragmentCount+"\" style=\"background-color: rgb(255, 255, 255); background: #000;border: none;height: calc(100vh - 63px);width: 100%;\"></iframe>"+
							"</div>"+
						    "<div class=\"modal-footer\" style=\"padding: 2px;\">"+
						      "<button type=\"button\"  data-dismiss=\"modal\" style=\"padding-right:25px;padding-left:25px;\" class=\"btn-xs btn-warning\" onclick=\"$('html').css('overflow','auto');\";>Close</button>"+
						    "</div>"+
						  "</div>"+
						"</div>"+
						"</div>";

					  } */
					  var fragId = "#fragment-"+fragmentCount;
					  $('#container-11').append(newDiv);
					  /* if($('#container-11 '+fragmentCount).length==0){
					  $('#container-11').append(newDiv);
					  }
					  else{
						  $('#container-11 '+fragmentCount).html(newDiv); 
					  }  */
					  /* if(isDownloadUploadRequired=="Y"&&tabType!=null && tabType.toLowerCase() == "listing"){
						  var uploadDIv ="<div id='txtUpload"+fragmentCount+"'><input type='file' name='txtUploadFilePath"+fragmentCount+"' id='txtUploadFilePath"+fragmentCount+"'><a href='#fragment-"+fragmentCount+"' class = 'green-btn' onclick=\"fnUploadChildForm('"+listFormId+"','"+tabListForm+"','"+fragmentCount+"')\"><span class=\"upload-icon\">&nbsp;</span>Upload</a><span id='txtMsgSpan"+fragmentCount+"'></span></div>";
						  $("#table-"+fragmentCount).append(uploadDIv);
					  } */
				}
				if(tabType==null)
					tabType = "";
					//document.getElementById("loginField").value= loginField;
					//console.log("loginField value = "+loginField);
			if(tabType.toLowerCase() == "courses" || tabType.toLowerCase() == "communities"  || tabType.toLowerCase() == "managecourses"){
			var loginField = pdfTabList[i].getAttribute("loginField");	
			if (loginField.includes('.'))
				document.getElementById("loginField").value= loginField.split('.')[1];
			else
				document.getElementById("loginField").value= loginField
				
			newTab = "<li ";
			if(tabType.toLowerCase() == "courses")
			{
				if(subsOnClick == "")
					{
						newTab = newTab + "onclick=\"fnGetPvcData('courses','','1')\"";//fnGetPvcData('courses','','1')
						newTab = newTab +"><a href='#fragment-"+fragmentCount+"'  ";//onclick=\"fnGetPvcData('courses','','1')\"
					}
				else
					{
						newTab = newTab + "onclick=\""+subsOnClick+"\"";//fnGetPvcData('courses','','1')
						newTab = newTab +"><a href='#fragment-"+fragmentCount+"'  ";//onclick=\""+subsOnClick+"\"
					}
			}
			if(tabType.toLowerCase() == "communities"){
				
				if(subsOnClick == "")
				{
					newTab = newTab + "onclick=\"fnGetPvcData('communities','','1')\"";//fnGetPvcData('communities','','1')
					newTab = newTab +"><a href='#fragment-"+fragmentCount+"'  ";//onclick=\"fnGetPvcData('communities','','1')\"
				}
				else 
				{
					newTab = newTab + "onclick=\""+subsOnClick+"\"";//fnGetPvcData('communities','','1')
					newTab = newTab +"><a href='#fragment-"+fragmentCount+"' ";// onclick=\""+subsOnClick+"\"
				}
			}
			
			if(tabType.toLowerCase() == "managecourses")
			{
				if(subsOnClick == "")
					{
						newTab = newTab + "onclick=\"fnGetPvcData('managecourses','','1')\"";//fnGetPvcData('courses','','1')
						newTab = newTab +"><a href='#fragment-"+fragmentCount+"'  ";//onclick=\"fnGetPvcData('managecourses','','1')\"
					}
				else
					{
						newTab = newTab + "onclick=\""+subsOnClick+"\"";//fnGetPvcData('courses','','1')
						newTab = newTab +"><a href='#fragment-"+fragmentCount+"'  ";//onclick=\""+subsOnClick+"\"
					}
			}
			
			
			//newTab = newTab +"><a href='#fragment-"+fragmentCount+"' ";
			newTab = newTab + " ><span id='"+tabId+"_Tab_Name' title = \""+tabName+"\">"+ tabName+"</span></a></li>";
			$('#tabs').append(newTab);
			notAnEmptyTab = true;
			if(tabType.toLowerCase() == "courses" || tabType=="managecourses"){
				fnGetTabForCourses(fragmentCount,tabDesc,tabId,tabType);
			}
			if(tabType.toLowerCase() == "communities"){
				//console.log(123);
				fnGetTabForCommunities(fragmentCount,tabDesc,tabId);
			}
			} 
			else if(tabType == "onlineAssessment")
			{
				if(subsOnClick == "")
					newTab = "<li onclick=\"fnGetOnlineAssessmentData('live','1')\"><a href='#fragment-"+fragmentCount+"'   ";//onclick=\"fnGetOnlineAssessmentData('live','1')\"
				else
				newTab = "<li onclick=\""+subsOnClick+"\"><a href='#fragment-"+fragmentCount+"' ";// onclick=\""+subsOnClick+"\" 
				
				newTab = newTab + " ><span id='"+tabId+"_Tab_Name' title = \""+tabName+"\">"+ tabName+"</span></a></li>";
				$('#tabs').append(newTab);
				notAnEmptyTab = true;
				fnGetTabForOnlineAssessment(fragmentCount,tabDesc,tabId);
							  					
			}
			else if(tabType == "QPPrintSubscription")
				{
				var applnSequenceField = $('#applnSequenceField').val();
				var orgID = $('#orgId').val();
				var formId = $('#formId').val();
				newTab = "<li onclick=\"fnGetQPPrintDataFW("+fragmentCount+","+applnSequenceField+","+formId+","+orgID+",'searchInput_QP','live','1')\"><a href='#fragment-"+fragmentCount+"'  ";//onclick=\"fnGetQPPrintDataFW("+fragmentCount+","+applnSequenceField+","+formId+","+orgID+",'live')\"
				newTab = newTab + " ><span id='"+tabId+"_Tab_Name' title = \""+tabName+"\">"+ tabName+"</span></a></li>";
				$('#tabs').append(newTab);
				notAnEmptyTab = true;
				fnGetTabForQP(fragmentCount,tabDesc,tabId);
						  					
				}
			/*code added for QP Print tab ends*/	
			else if(tabType.toLowerCase() == "lba")
			{
						newTab ="<li onclick=\"fnGetLBAData('lba','','1')\"";//fnGetPvcData('courses','','1')
						newTab = newTab +"><a href='#fragment-"+fragmentCount+"'  ";//onclick=\"fnGetPvcData('managecourses','','1')\"
						
						newTab = newTab + " ><span id='"+tabId+"_Tab_Name' title = \""+tabName+"\">"+ tabName+"</span></a></li>";
						$('#tabs').append(newTab);
						notAnEmptyTab = true;
						fnGetTabForLBA(fragmentCount,tabDesc,tabId);
				
			}
			//code for CUSTOM SUBSCRITPION TAB
			 else if(tabType !=("PDF/HTML") && tabType !=("Hall Ticket") && tabType != ("Slot booking") && tabType != ("Evaluation") && tabType !=("Question Paper Publish") && tabType.toLowerCase() != "listing" && tabType.toLowerCase() != "courses" && tabType.toLowerCase() != "communities" && tabType != "onlineAssessment" && tabType != "managecourses" && tabType != "lba")
				{
				
				if(subsOnClick == "")
					newTab = "<li onclick=\"\"><a href='#fragment-"+fragmentCount+"'   ";//onclick=\"fnGetOnlineAssessmentData('live','1')\"
				else
				newTab = "<li onclick=\""+subsOnClick+"\"><a href='#fragment-"+fragmentCount+"' ";// onclick=\""+subsOnClick+"\" 
				
				newTab = newTab + " ><span id='"+tabId+"_Tab_Name' title = \""+tabName+"\">"+ tabName+"</span></a></li>";
				$('#tabs').append(newTab);
				notAnEmptyTab = true;
				fnGetTabForCustomSubscriptionFW(fragmentCount,tabDesc,tabId,serviceID);
				
				} 
			
				
				
			if(tabType.toLowerCase() != "listing" && tabType.toLowerCase() != "courses" && tabType.toLowerCase() != "communities" && tabType != "onlineAssessment" && tabType != "managecourses" &&  tabType != "lba"){
			  //var constantVar=1;
				for(var pdfCount=0;pdfCount< pdfList.length;pdfCount++){
			    var pdfLinkNameDocs  = pdfList[pdfCount].getElementsByTagName("PDFLINKNAME");
				var pdfIdentifierDocs  = pdfList[pdfCount].getElementsByTagName("PDFIDENTIFIER");
				var html  = pdfList[pdfCount].getElementsByTagName("HTML");
				var htmlPdfIdentifier  = pdfList[pdfCount].getElementsByTagName("HTMLPDFIDENTIFIER");
				var dateFormat = pdfList[pdfCount].getElementsByTagName("DATEFORMAT");
				var isPrintable = pdfList[pdfCount].getElementsByTagName("ISPRINTABLE");
				var pdfStartDateDocs = pdfList[pdfCount].getElementsByTagName("PDFSTARTDATE");
				var pdfEndDates = pdfList[pdfCount].getElementsByTagName("PDFENDDATE");
				var staticText1Docs = pdfList[pdfCount].getElementsByTagName("PDFSTATICTEXT1");
				var staticText2Docs = pdfList[pdfCount].getElementsByTagName("PDFSTATICTEXT2");
				try{
				for(var tagCount=0;tagCount<pdfIdentifierDocs.length;tagCount++){
				if(htmlPdfIdentifier[tagCount].firstChild){
					if (htmlPdfIdentifier[tagCount].firstChild.nodeValue!=null){
				if(htmlPdfIdentifier[tagCount].firstChild.nodeValue!="html")
				{
					
				var linkToInsert = "<tr><td>";
				
				if(pdfList[pdfCount].getElementsByTagName("HTML")[tagCount].firstChild!=null && pdfList[pdfCount].getElementsByTagName("HTML")[tagCount].firstChild.nodeValue!="" && pdfList[pdfCount].getElementsByTagName("HTML")[tagCount].firstChild.nodeValue!="-" && htmlPdfIdentifier[tagCount].firstChild.nodeValue=="expro")
					{
					var htmlStringValue=pdfList[pdfCount].getElementsByTagName("HTML")[tagCount].firstChild.nodeValue+"";
				var htmlBeforeLink=htmlStringValue.split("@ion@PDFExproLinkName@ion@")[0];
				var linkName=htmlStringValue.split("@ion@PDFExproLinkName@ion@")[1];
				var htmlAfterLink=htmlStringValue.split("@ion@PDFExproLinkName@ion@")[2];
				
				linkToInsert = linkToInsert +	htmlBeforeLink + " ";
				if(pdfIdentifierDocs[tagCount].firstChild){
					 linkToInsert = linkToInsert + "<a href='#fragment-"+fragmentCount+"' style=\" color: #0683c7;cursor:pointer;\" onclick=\"" + pdfIdentifierDocs[tagCount].firstChild.nodeValue + "\"> ";}
				 linkToInsert = linkToInsert + linkName + "</a>";	
				 linkToInsert = linkToInsert + htmlAfterLink;
				 
					}
				
				else
					{
				if(staticText1Docs[tagCount].firstChild){
				 linkToInsert = linkToInsert +	staticText1Docs[tagCount].firstChild.nodeValue + " ";}
				 if(pdfIdentifierDocs[tagCount].firstChild){
				 linkToInsert = linkToInsert + "<a href='#fragment-"+fragmentCount+"' style=\" color: #0683c7;cursor:pointer;\" onclick=\"" + pdfIdentifierDocs[tagCount].firstChild.nodeValue + "\"> ";}
				 if(pdfLinkNameDocs[tagCount].firstChild){
				 linkToInsert = linkToInsert + pdfLinkNameDocs[tagCount].firstChild.nodeValue + "</a>";}
				 if(staticText2Docs[tagCount].firstChild){
				 linkToInsert = linkToInsert + staticText2Docs[tagCount].firstChild.nodeValue;}
					}
				 
				 linkToInsert = linkToInsert + "</td></tr>";
				// $("#table-"+fragmentCount).append(linkToInsert);
				if( layout_identifier=='' && $("#"+layout_identifier + "_content")==null ||  $("#"+layout_identifier + "_content").html()==undefined){
					if( $("#table-"+fragmentCount)==null ||  $("#table-"+fragmentCount).html()==undefined){
						linkToInsert = "<table id='#table-"+fragmentCount+"' width='100%' cellspacing='0' cellpadding='0' border='0' style='background-color: #eaf4f9;border: 1px solid #97A5B0;' class='info_table'><body>" + linkToInsert + "</tbody></table>";
						$("#fragment-"+fragmentCount).append(linkToInsert);
					}else{
						$("#table-"+fragmentCount).append(linkToInsert);
					}
				  }else{
					$("#"+layout_identifier + "_content").append(linkToInsert);	
				  } 
				
				}
				else
				{
				var linkToInsert = "";
				if(staticText1Docs[tagCount].firstChild!= null && pdfLinkNameDocs[tagCount].firstChild!=null  && staticText2Docs[tagCount].firstChild !=null)
				{

				if( staticText1Docs[tagCount].firstChild.nodeValue!=null  && staticText1Docs[tagCount].firstChild.nodeValue!=("") && pdfLinkNameDocs[tagCount].firstChild.nodeValue!=null && pdfLinkNameDocs[tagCount].firstChild.nodeValue!=("") && staticText2Docs[tagCount].firstChild.nodeValue!=null && staticText2Docs[tagCount].firstChild.nodeValue!=("")){
					linkToInsert = linkToInsert+"<tr><td>";
				linkToInsert = linkToInsert +	staticText1Docs[tagCount].firstChild.nodeValue + " ";
				
				linkToInsert = linkToInsert + "<a href='#fragment-"+fragmentCount+"' style=\" color: #0683c7;cursor:pointer;\" onclick=\"" + pdfIdentifierDocs[tagCount].firstChild.nodeValue + "\"> ";
		
				linkToInsert = linkToInsert + pdfLinkNameDocs[tagCount].firstChild.nodeValue + "</a>";
				
				linkToInsert = linkToInsert + staticText2Docs[tagCount].firstChild.nodeValue;
				linkToInsert = linkToInsert + "</td></tr>";
				}
			}
				else
					{
				
					var htmlClass="ConfiguredHtmlContent";
					var htmlIds="ConfiguredHtmlContent";
					htmlIds=htmlIds+constantVar;
					linkToInsert = linkToInsert+"<tr><td class="+htmlClass+" id="+htmlIds+">";
					var xmlFilePath=html[tagCount].firstChild.nodeValue;
					var formatForDate = "";
					if (dateFormat[tagCount].firstChild)
					{var formatForDate = dateFormat[tagCount].firstChild.nodeValue;}
					if (isPrintable[tagCount].firstChild){var isPrintableFlag = isPrintable[tagCount].firstChild.nodeValue;}
					if(isPrintableFlag == "Y")
					{
					jQuery("#print"+fragmentCount).css("display","block");
					}
	// 				xmlFilePath=xmlFilePath.replace("/AppData/StaticContent/EForms/configuredXML/","/EForms/configuredXML/");//stuti's change
					var xmlDoc=htmlData(xmlFilePath);
					var x=xmlDoc.getElementsByTagName("RESPONSE");
	                         var htmlContent="";
	                        for (j=0;j<x.length;j++)
	                        { 
	                                htmlContent=x[j].getElementsByTagName("HTMLCONTENT")[0].childNodes[0].nodeValue;
	                                htmlContent.replace("&lt;","<");
	                                htmlContent.replace("&gt;",">");
	                        }
					 linkToInsert= linkToInsert+ htmlContent;
					 linkToInsert=  linkToInsert + "</td></tr>";
					  constantVar++; 
					  var dateFormatId = htmlIds + "a";
					  linkToInsert =linkToInsert+ "<tr><td><br/></td><td id ="+dateFormatId+" style='display:none;' >"+formatForDate+"</td></tr>";
					  
				}	
				  if( layout_identifier=='' && $("#"+layout_identifier + "_content")==null ||  $("#"+layout_identifier + "_content").html()==undefined){
					if( $("#table-"+fragmentCount)==null ||  $("#table-"+fragmentCount).html()==undefined){
						linkToInsert = "<table id='#table-"+fragmentCount+"' width='100%' cellspacing='0' cellpadding='0' border='0' style='background-color: #eaf4f9;border: 1px solid #97A5B0; padding-left:0px;' class='info_table'><body>" + linkToInsert + "</tbody></table>";
						$("#fragment-"+fragmentCount).append(linkToInsert);
					}else{
						$("#table-"+fragmentCount).append(linkToInsert);
					}
				  }else{
					$("#"+layout_identifier + "_content").append(linkToInsert);	
				  } 						 
				}
				}
				}else{
					var linkToInsert = "<tr><td>";
				if(staticText1Docs[tagCount].firstChild){
				 linkToInsert = linkToInsert +	staticText1Docs[tagCount].firstChild.nodeValue + " ";}
				 if(pdfIdentifierDocs[tagCount].firstChild){
				 linkToInsert = linkToInsert + "<a href='#fragment-"+fragmentCount+"' onclick='" + pdfIdentifierDocs[tagCount].firstChild.nodeValue + "'> ";}
				 if(pdfLinkNameDocs[tagCount].firstChild){
				 linkToInsert = linkToInsert + pdfLinkNameDocs[tagCount].firstChild.nodeValue + "</a>";}
				 if(staticText2Docs[tagCount].firstChild){
				 linkToInsert = linkToInsert + staticText2Docs[tagCount].firstChild.nodeValue;}
				 linkToInsert = linkToInsert + "</td></tr>";
				 linkToInsert = linkToInsert + "</tbody></table>";
				 //$("#"+layout_identifier + "_content").append(linkToInsert);	
				// $("#table-"+fragmentCount).append(linkToInsert);
				if( layout_identifier=='' || $("#"+layout_identifier + "_content")==null ||  $("#"+layout_identifier + "_content").html()==undefined){
					if( $("#table-"+fragmentCount)==null ||  $("#table-"+fragmentCount).html()==undefined){
						linkToInsert = "<table id='#table-"+fragmentCount+"' width='100%' cellspacing='0' cellpadding='0' border='0' style='background-color: #eaf4f9;border: 1px solid #97A5B0; padding-left:0px;' class='info_table'><body>" + linkToInsert + "</tbody></table>";
						$("#fragment-"+fragmentCount).append(linkToInsert);
					}else{
						$("#table-"+fragmentCount).append(linkToInsert);
					}
				  }else{
					$("#"+layout_identifier + "_content").append(linkToInsert);	
				  } 
				
				}
				}
				}catch(e){
					console.log(e);
				}
				if(tabName!=null && tabName=="Test Slot Booking"){
			  		document.getElementById('slotBkngTabId').value="fragment-"+fragmentCount;
			  	}
			  	if(tabName!=null && tabName=="Hall Ticket"){
			  		document.getElementById('hallTcktTabId').value="fragment-"+fragmentCount;
			  	}
			  	if(tabName!=null && tabName=="Question Paper"){
			  		document.getElementById('qpPblishTabId').value="fragment-"+fragmentCount;
			  	}
				
			  }
		}
			  }
			  try{
			  
				  if(tabLayout=="horizontalWithIcon"){
					  var TabHeading="";
					  if(notAnEmptyTab){
						TabHeading = $('#tabs li:last span:first').html().trim();
						//console.log(TabHeading);
						var linkRef=$('#tabs li:last a').attr('href');
						var functionOnClick=$('#tabs li:last a').attr('onclick');
						
						var tabLiLastContent='<a id='+linkRef+' href=javascript:goToTopWithLink() onclick='+functionOnClick+' ><div class="Absolute-Center clearfix"><div class="tabicon">';
						if(iconPath==null || iconPath==""){	
							tabLiLastContent=tabLiLastContent+'<i class="ansscript"></i>';
						}else{
							tabLiLastContent=tabLiLastContent+' <img src="'+iconPath+'" alt="'+iconPath+'" height="27" width="20"> ';
						}
						tabLiLastContent=tabLiLastContent+'</div><div class="tabtext sansSB" ><span id="'+tabId+'_Tab_Name" title="'+TabHeading+'">'+TabHeading+'</span></div></div></a>';
						$('#tabs li:last').html(tabLiLastContent);
						$('#tabs li:last').attr('role','presentation');
						$('#tabs li:last').attr('class','js-tab');
						}
						}
					    if(tabLayout=="horizontalWithoutIcon"){
						  var TabHeading="";
						  if(notAnEmptyTab){
							TabHeading = $('#tabs li:last span:first').html().trim();
							//console.log(TabHeading);
							var linkRef=$('#tabs li:last a').attr('href');
							var functionOnClick=$('#tabs li:last a').attr('onclick');
							
							var tabLiLastContent='<a id='+linkRef+' href=javascript:goToTopWithLink() onclick='+functionOnClick+' ><div class="Absolute-Center clearfix"><div class="tabicon"></div>';
							tabLiLastContent=tabLiLastContent+'<div class="tabtext sansSB" style="text-align:center; padding:4px 7px 0 24px" ><span id="'+tabId+'_Tab_Name" title="'+TabHeading+'">'+TabHeading+'</span></div></div></a>';
							$('#tabs li:last').html(tabLiLastContent);
							$('#tabs li:last').attr('role','presentation');
							$('#tabs li:last').attr('class','js-tab');
							}
							}
					    if(tabLayout=="verticalWithIcon"){
							  var TabHeading="";
							  if(notAnEmptyTab){
								TabHeading = $('#tabs li:last span:first').html().trim();
								//console.log(TabHeading);
								var linkRef=$('#tabs li:last a').attr('href');
								var functionOnClick=$('#tabs li:last a').attr('onclick');
								
								var tabLiLastContent='<a id='+linkRef+' href=javascript:goToTopWithLink() onclick='+functionOnClick+' ><div class="Absolute-Center clearfix"><div class="tabicon">';
								if(iconPath==null || iconPath==""){	
									tabLiLastContent=tabLiLastContent+'<i class="ansscript"></i>';
								}else{
									tabLiLastContent=tabLiLastContent+' <img src="'+iconPath+'" alt="'+iconPath+'" height="27" width="20"> ';
								}
								tabLiLastContent=tabLiLastContent+'</div><div class="tabtext sansSB" ><span id="'+tabId+'_Tab_Name" title="'+TabHeading+'">'+TabHeading+'</span></div></div></a>';
								$('#tabs li:last').html(tabLiLastContent);
								$('#tabs li:last').attr('role','presentation');
								$('#tabs li:last').attr('class','js-tab');
								}
								}
									if(tabLayout=="verticalWithoutIcon"){
								  var TabHeading="";
								  if(notAnEmptyTab){
									TabHeading = $('#tabs li:last span:first').html().trim();
									//console.log(TabHeading);
									var linkRef=$('#tabs li:last a').attr('href');
									var functionOnClick=$('#tabs li:last a').attr('onclick');
									
									var tabLiLastContent='<a id='+linkRef+' href=javascript:goToTopWithLink() onclick='+functionOnClick+' ><div class="Absolute-Center clearfix"><div class="tabicon"></div>';
									tabLiLastContent=tabLiLastContent+'<div class="tabtext sansSB" style="text-align:left; padding:4px 7px 0 24px" ><span id="'+tabId+'_Tab_Name" title="'+TabHeading+'">'+TabHeading+'</span></div></div></a>';
									$('#tabs li:last').html(tabLiLastContent);
									$('#tabs li:last').attr('role','presentation');
									$('#tabs li:last').attr('class','js-tab');
									}
									}
				if(tabLayout == "vertical"){ 
					  var TabHeading = $('#tabs li:last span:first').html().trim();
					  var linkRef=$('#tabs li:last a').attr('href');
					  $('#tabs li:last').html('<a href='+linkRef+' style="cursor:pointer;text-decoration: none"><span class=\'vertical_span\' style=\"background: url(\'/EForms/images/icons/all-hover.png\') no-repeat scroll center center transparent;\">&nbsp;</span><span  class=\"vertical_label\" >'+TabHeading+'</span></a>');
					  $('#tabs li:last').width($('ul li:first').width());
				} 
				
				
			  }catch(e){
				  console.log($('#tabs li:last').html());
			  }
		}
		
		loadHorizontalTabs();
		var tabColor = '#5d9bfb';
		var tabColorOnhover = '#ffffff';
		var tabTextColor = '#ffffff';
		var tabTextColorOnhover = '#333';
		
		customizeHorizontalTabs(tabColor,tabColorOnhover,tabTextColor,tabTextColorOnhover);
		
		
	}
}


	
	
		function getViewDetails(orgId,formId){
			
			
			if(typeof window.getViewDetailsFrameworkBefore == 'function') {
				getViewDetailsFrameworkBefore(orgId,formId);
			   }
		$('#loader-indicator').show();
		eval(displayHTML());
		var displayProfile=document.getElementById("strDisplayProfile").value;
		displayProfile=replaceCData(displayProfile);
		var responseDoc=fnStringtoXML(displayProfile);  
		
	
		var docs = responseDoc.getElementsByTagName("FIELD");
		var noOfDocuments=docs.length;
		if(noOfDocuments > 0){					 
			for(count=0;count<noOfDocuments;count++)		//loop document
			{
				var dochtmlName=docs[count].getElementsByTagName("HTMLNAME");
				var dochtmlValue=docs[count].getElementsByTagName("VALUE");
				var dochtmlDataType=docs[count].getElementsByTagName("DATATYPE");
				var applnSequenceFieldChk="N";
				if(docs[count].getAttribute("applnSequenceField")!=null)
					applnSequenceFieldChk = docs[count].getAttribute("applnSequenceField");
						
					var htmlElement=dochtmlName[0].firstChild.nodeValue;
					var htmlElementName=htmlElement+"_div";
					var trElement=htmlElement+"_tr";
					
					/*Replace HTML Format Configuration Variables: Start*/
					var className=htmlElement+"_class";
					var htmlClassName="ConfiguredHtmlContent";
					var eleArr=getElementsByClassNme(className,document.body);
					var eleArrClass=getElementsByClassNme(htmlClassName,document.body);
					
					
					if(dochtmlValue[0].firstChild!=null){
						var htmlElementValue=dochtmlValue[0].firstChild.nodeValue;
						var forFormatting = htmlElementValue;
						var dataTypeCheck = "";
						if(dochtmlDataType[0]!=null && dochtmlDataType[0].firstChild!=null)
							dataTypeCheck = dochtmlDataType[0].firstChild.nodeValue;
						
						var htmlVariable;
						if (/\S/.test(htmlElementValue)) {
						if(trim(htmlElementValue)!="")
							 htmlVariable="@@ConfiguredHTML_"+htmlElement+"@@";
							}
						else{
							htmlVariable="";
							}							
						
						
						
						
						
						
						if(dataTypeCheck=="datetime"){
								if(htmlElementValue!='//null' && htmlElementValue!='null'){
									if(htmlElementValue.indexOf("-")>0)
									{
								if('dd/mm/yyyy'=='' || 'dd/mm/yyyy'=='mm/dd/yyyy' || 'dd/mm/yyyy'==null)
								{												
								var appDobY=htmlElementValue.substring(0,4);
	    						var appDobM=htmlElementValue.substring(5,7);
	    						var appDobD=htmlElementValue.substring(8,10);
	    						if(document.getElementById(htmlElementName)!=null){
	    							htmlElementValue= appDobD + "/" + appDobM + "/" + appDobY ;
	    						}
	    						}
	    						if('dd/mm/yyyy'=='dd/mm/yyyy' && 'dd/mm/yyyy'!=null)
								{	
									
								var appDobY=htmlElementValue.substring(0,4);
	    						var appDobM=htmlElementValue.substring(5,7);
	    						var appDobD=htmlElementValue.substring(8,10);
								  
	    						if(document.getElementById(htmlElementName)!=null){
	    							htmlElementValue= appDobD + "/" + appDobM + "/" + appDobY ; 
	    						}
	    						}
	    						}
						}
							}
						
						
						
						
						
						for(var i=0;i<eleArrClass.length;i++)
							{
								var htmlIds=eleArrClass[i].getAttribute("id");
								var htmlContent=document.getElementById(htmlIds).innerHTML;
								if(dataTypeCheck=="datetime" && htmlContent!="null" && htmlContent!='null' && htmlContent.indexOf("-")>0){
									var dateFormatId = htmlIds + "a";
										if(trim(htmlVariable)!="")
									{
									
									var formattedDate=""; 
									var dateFormat = document.getElementById(dateFormatId).innerHTML;
		switch (dateFormat) {
		    case "dd/MMM/yyyy":
		    	dateFormat = "dd/M/yy";
		        break;
		    case "Ddth mmm yyyy":
		    	formattedDate=Dt+getOrdinalSuffix(Dt)+" "+getShortMonth(mon)+" "+Year;
		        break;
		    case "dd MMM yyyy":
		    	dateFormat = "dd M yy";
		        break;
		    case "dd MMM yy":
		    	dateFormat = "dd M y";
		        break;
		    case "dd-MM-yyyy":
		    	dateFormat = "dd-mm-yy";
		        break;
		    case "dd-MM-yy":
		    	dateFormat = "dd-mm-y";
		        break;
		    case "dd/MM/yyyy":
		    	dateFormat = "dd/mm/yy";
		        break;
		    case "dd/MM/yy":
		    	dateFormat = "dd/mm/y";
		        break;
		    case "Ddth month yyyy":
		    	formattedDate=Dt+getOrdinalSuffix(Dt)+" "+getLongMonth(mon)+" "+Year;
		        break;
		    case "dd MMMMM yyyy":
		    	dateFormat = "dd MM yy";
		        break;
		    case "dd MMMMM yy":
		    	dateFormat = "dd MM y";
		        break;
		    case "MMM dd, yyyy":
		    	dateFormat = "M dd, yy";
		        break;
		    case "MMMMM dd, yyyy":
		    	dateFormat = "MM dd, yy";
		        break;
		    case "Mmm ddth, yyyy":
		    	formattedDate=getShortMonth(mon)+" "+Dt+getOrdinalSuffix(Dt)+", "+Year;
		        break;
		    case "Month ddth, yyyy":
		    	formattedDate=getLongMonth(mon)+" "+Dt+getOrdinalSuffix(Dt)+", "+Year;
		        break;
		    case "MM-dd-yyyy":
		    	dateFormat = "mm-dd-yy";
		        break;
		    case "MM-dd-yy":
		    	dateFormat = "mm-dd-y";
		        break;
		    case "MM/dd/yyyy":
		    	dateFormat = "mm/dd/yy";
		        break;
		    case "MM/dd/yy":
		    	dateFormat = "mm/dd/y";
		        break;
		    case "dd/MMMMM/yyyy":
		    	dateFormat = "dd/MM/yy";
		        break;
		    case "dd/MMMMM/yy":
		    	dateFormat = "dd/MM/y";
		        break;
		    case "dd/MMM/yy":
		    	dateFormat = "dd/M/y";
		        break;
		    default : 
		    	dateFormat = "dd/M/yy";
		    	break;}
									 formattedDate = $.datepicker.formatDate(dateFormat, new Date(forFormatting.split(' ')[0]));
									htmlContent=replaceAll(htmlContent,htmlVariable,formattedDate);
									}
									else
									{
										var	htmlElementTemp = "@@ConfiguredHTML_"+htmlElement+"@@";
										htmlContent=replaceAll(htmlContent,htmlElementTemp,"");
										//document.getElementById(htmlIds).innerHTML="";
										//continue;
									}
									
									}
								else{
								if(trim(htmlVariable)!="")
								{
								htmlContent=replaceAll(htmlContent,htmlVariable,htmlElementValue);
								}
								else
								{
								var	htmlElementTemp = "@@ConfiguredHTML_"+htmlElement+"@@";
								htmlContent=replaceAll(htmlContent,htmlElementTemp,"");
								//document.getElementById(htmlIds).innerHTML="";
								//continue;
								}}
								document.getElementById(htmlIds).innerHTML=htmlContent;
								if(eleArrClass[i].tagName=="img" || eleArrClass[i].tagName=="IMG")
								{
									eleArr[k].setAttribute("src", htmlElementValue);
								}
							}
							for(var k=0;k<eleArr.length;k++)
							{
								var id=eleArr[k].getAttribute("id");
								if(eleArr[k].tagName=="img" || eleArr[k].tagName=="IMG")
								{
									eleArr[k].setAttribute("src", htmlElementValue);
								}
								else
								{
								   document.getElementById(id).innerHTML=htmlElementValue;
								}
								
							}
					}
					else{
					for(var i=0;i<eleArrClass.length;i++)
							{
								var htmlIds=eleArrClass[i].getAttribute("id");
								var htmlContent=document.getElementById(htmlIds).innerHTML;
								htmlElementTemp = "@@ConfiguredHTML_"+htmlElement+"@@";
								if(trim(htmlElement)!="")
								{
								htmlContent=replaceAll(htmlContent,htmlElementTemp,"");
								}
								else
								{
								document.getElementById(htmlIds).innerHTML="";
								continue;
								}
								document.getElementById(htmlIds).innerHTML=htmlContent;
								
							}
								
					}
					
					/*Replace HTML Variables: End*/
					if(htmlElement=="txtPhotoPath"){
						if(dochtmlValue[0].firstChild!=null){
							if((dochtmlValue[0].firstChild.nodeValue!=null)&&(dochtmlValue[0].firstChild.nodeValue)!='null'){
								var htmlElementValue=dochtmlValue[0].firstChild.nodeValue;
								if(document.getElementById(trElement)!=null){
									if(htmlElementValue!=null && htmlElementValue.indexOf("/EFormsServeImage")==-1)
									document.getElementById("appPhotoImgPath").src=htmlElementValue+"?v="+19;
									else 
										document.getElementById("appPhotoImgPath").src=htmlElementValue+"&sessChk="+$("#sessChk").val();
								}
							}
							else{
								if(document.getElementById(trElement)!=null){
									document.getElementById("appPhotoImgPath").src='images/onlineAppForm/nophoto.gif';
								}
							}
						}				 
					}
					else if(htmlElement=="txtSignaturePath"){
						if(dochtmlValue[0].firstChild!=null){
							if((dochtmlValue[0].firstChild.nodeValue!=null)&&(dochtmlValue[0].firstChild.nodeValue)!='null'){
								var htmlElementValue=dochtmlValue[0].firstChild.nodeValue;
								if(document.getElementById(trElement)!=null){
									if(htmlElementValue!=null && htmlElementValue.indexOf("/EFormsServeImage")==-1)
										document.getElementById("appSignaturePath").src=htmlElementValue+"?v="+19;
										else 
											document.getElementById("appSignaturePath").src=htmlElementValue+"&sessChk="+$("#sessChk").val();
									
								}
							}
							else{
								if(document.getElementById(trElement)!=null){
								document.getElementById(trElement).style.display='none';
								}
							}
						}				 
					}
					else if(htmlElement=="txtThumbpath"){
						if(dochtmlValue[0].firstChild!=null){
							if((dochtmlValue[0].firstChild.nodeValue!=null)&&(dochtmlValue[0].firstChild.nodeValue)!='null'){
								var htmlElementValue=dochtmlValue[0].firstChild.nodeValue;
								if(document.getElementById(trElement)!=null){
									if(htmlElementValue!=null && htmlElementValue.indexOf("/EFormsServeImage")==-1)
										document.getElementById("appThumbpath").src=htmlElementValue+"?v="+19;
										else 
											document.getElementById("appThumbpath").src=htmlElementValue+"&sessChk="+$("#sessChk").val();
									
									
								}
							}
							else{
								if(document.getElementById(trElement)!=null){
								}
							}
						}				 
					}
					else if(htmlElement=="entity_Id"){
						if(dochtmlValue[0].firstChild!=null){
							var htmlElementValue=dochtmlValue[0].firstChild.nodeValue;
							document.getElementById("entityId").value=htmlElementValue;
						}
					}
					else if(htmlElement=="txtCourses"){
						if(dochtmlValue[0].firstChild!=null){
							var htmlElementValue=dochtmlValue[0].firstChild.nodeValue;
							if(document.getElementById('txtCourses_div')!=null){
								document.getElementById('txtCourses_div').innerHTML=htmlElementValue;
							}
							if(document.getElementById('txtCourses')!=null){
								document.getElementById('txtCourses').value=htmlElementValue;
							}
						}
					}else if(applnSequenceFieldChk=="Y"){
						if(dochtmlValue[0].firstChild!=null){
							var htmlElementValue=dochtmlValue[0].firstChild.nodeValue;
							if((htmlElementValue!="")&&(htmlElementValue!=null)&& document.getElementById(htmlElementName)!=null){
								document.getElementById(htmlElementName).innerHTML=htmlElementValue;
							}
							if(document.getElementById(htmlElement)!=null){
								document.getElementById(htmlElement).value=htmlElementValue;
							}
						}
					}
					
					else if(htmlElement=="checksum"){
						if(dochtmlValue[0].firstChild!=null){
							var htmlElementValue=dochtmlValue[0].firstChild.nodeValue;
							if(document.getElementById('checksum')!=null){
								document.getElementById('checksum').value=htmlElementValue;
							}
						}
					}
					else{			
						if(dochtmlValue[0].firstChild!=null){
							var htmlElementValue=dochtmlValue[0].firstChild.nodeValue;
							var dataType="";
							if(dochtmlDataType[0].firstChild!=null){
								dataType = dochtmlDataType[0].firstChild.nodeValue;
							}
							if(dataType=="datetime"){
								if(htmlElementValue!='//null' && htmlElementValue!='null' && htmlElementValue.indexOf("-")>0){
								if('dd/mm/yyyy'=='' || 'dd/mm/yyyy'=='mm/dd/yyyy' || 'dd/mm/yyyy'==null)
								{												
								var appDobY=htmlElementValue.substring(0,4);
	    						var appDobM=htmlElementValue.substring(5,7);
	    						var appDobD=htmlElementValue.substring(8,10);
	    						if(document.getElementById(htmlElementName)!=null){
	    							document.getElementById(htmlElementName).innerHTML=appDobM + "/" + appDobD + "/" + appDobY;
	    						}
	    						}
	    						if('dd/mm/yyyy'=='dd/mm/yyyy' && 'dd/mm/yyyy'!=null)
								{	
									
								var appDobY=htmlElementValue.substring(0,4);
	    						var appDobM=htmlElementValue.substring(5,7);
	    						var appDobD=htmlElementValue.substring(8,10);
								  
	    						if(document.getElementById(htmlElementName)!=null){
	    							document.getElementById(htmlElementName).innerHTML=appDobD + "/" + appDobM + "/" + appDobY;
	    						}
	    						}
	    						}
								else
									{
									if(document.getElementById(htmlElementName)!=null){
		    							document.getElementById(htmlElementName).innerHTML=htmlElementValue;
		    						}
									}
							}
							else{
								if(document.getElementById(htmlElementName)!=null){
									if((htmlElementValue!=null) && (htmlElementValue!="")){
										document.getElementById(htmlElementName).innerHTML=htmlElementValue;
									}
								}
							}
							if(htmlElement=="app_status"){
						if(dochtmlValue[0].firstChild!=null){
							if((htmlElementValue!=null) && (htmlElementValue!="")){
								if(document.getElementById("curr_app_status")!=null){
									document.getElementById("curr_app_status").innerHTML=htmlElementValue;
								}
							}
						}
					}
					if(htmlElement=="comments"){
						if(dochtmlValue[0].firstChild!=null){
							if((htmlElementValue!=null) && (htmlElementValue!="")){
								if(document.getElementById("curr_app_comments")!=null){
									document.getElementById("curr_app_comments").innerHTML=htmlElementValue;									
								}
							}
							
						}
					}	
					if(document.getElementById("curr_app_comments")!=null){
								if(document.getElementById("curr_app_comments").innerHTML==""){
									document.getElementById("curr_app_comments").innerHTML="No Comments Found";
								}
							}		
							
						}
						else{
							if(document.getElementById(trElement)!=null){
								document.getElementById(trElement).style.display='none';
							}
						}
					}
			}
		}
	
			document.getElementById("strDisplayProfile").value="";
			
			jQuery('#container .customMenuH li a, #tabDropdown li a').each(function(e){
				
			jQuery(this).click(function(){
				jQuery('#container li').removeClass('tabs-selected');
				jQuery(this).parent().addClass('tabs-selected');
				jQuery('.tabs-container').hide();
				
				
				var ids = this.id;
				jQuery('.tabs-container'+ids).show();
				
				
				});
			}); 
			
			jQuery('#container li').eq(displayCount).find('a').click();
			setTimeout(function() {$('#loader-indicator').hide();if(opener)opener.$(opener.document).trigger('loaded'); },500);
			
			
			
			if(typeof window.getViewDetailsFrameworkAfter == 'function') {
				getViewDetailsFrameworkAfter();
			   }
			
		}
		
		
	   var totalPages="";
          var pageStart="";
          var totalPagesForPaging ="";
          var totalAllowedPages ="";
          var nextID ="";
          var previousID = "";
          var isNext ="";
          var isPrevious = "";
          var recordCount = "";
          var pageLimit = "";
          var page="";
          var sortingField="";
          var sortingFieldOrder = "";
          var dataFieldsCount = "";
			var fragmentid ="";
			var whereCondition = "";
			 var codedtabcalled = "0";
	
			function displayFWCodedTabs(fragId){
				if(($("#"+fragId).find("#hallTicket") != undefined || $("#"+fragId).find("#asmSlotBooking") != undefined) && codedtabcalled==0){
				
					createDiv();
					codedtabcalled=1;
				
				}
				
			}  

	
			$(document).ready(function(){
				$('body').find("div:first-child").css('background-color','');		
					});

			
	
	
		</script>
</head>









<body
	onload='getViewDetails(1936,76621);;'>


<input type="hidden" id="pValidationServletVal" name="pValidationServletVal" value="" />
<form name="loginForm" method="post" action="/EForms/loginAction.do"><div><input type="hidden" name="org.apache.struts.taglib.html.TOKEN" value="816d206ad10fb541bab42801aeae5efc"></div>
	<div style="text-align: center; color: rgb(0, 0, 0); position: fixed; z-index: 1000; display: none; background: rgba(255, 255, 255, .4) 50% 50% no-repeat; width: 100%; height: 100%;" id="loader-indicator">
		<img style="margin-right: 5px; position: relative; top: 200px;" src="images/onlineAppForm/loader.gif" />
	</div>
	<div style="text-align: center; color: rgb(0, 0, 0); position: fixed; z-index: 1000; display: none; background: rgba(255, 255, 255, .4) 50% 50% no-repeat; width: 100%; height: 100%;" id="loadz-indicator">
		<img style="margin-right: 5px; position: relative; top: 200px;" src="images/onlineAppForm/newDotLoader.gif" />
	</div>
	<div id="printform">
	<div class="project-overlay "></div>
	 
	 
	<input type="hidden" name="strDisplayProfile" value="&lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;&lt;RESPONSE&gt;
&lt;ANSWERSHEET/&gt;&amp;gt;&lt;HALLTICKET/&gt;&amp;gt;&lt;SUBJECTS/&gt;&amp;gt;&lt;ASSESSMENTSFORHT/&gt;&amp;gt;&lt;ASSESSMENTSFORSC/&gt;&amp;gt;&lt;ASSESSMENTSFORQP/&gt;&amp;gt;&lt;PDFGENERATION/&gt;&amp;gt;&lt;FORMCONFIGURATION&gt;
&lt;SHOWDEFAULTTAB&gt;Y&lt;/SHOWDEFAULTTAB&gt;
&lt;/FORMCONFIGURATION&gt;&amp;gt;&lt;FIELD&gt;
&lt;HTMLNAME&gt;entity_Id&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt; &lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.entity_id&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;N&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;N&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[27256]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;entityId&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt; &lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.entity_id&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;N&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;N&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[27256]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD applnSequenceField=&quot;Y&quot;&gt;
&lt;HTMLNAME&gt;app_seq_no&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Application No.&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.app_seq_no&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;N&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;N&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[P0027256]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;checksum&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt; &lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;checksum&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;N&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;N&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[H2A3%2B0C%2FnRFL0i2EVwO2MA%3D%3D]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;app_status&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Application Status&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.app_status&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[Pending]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;comments&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt; &lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.comments&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;N&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;logged_date&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt; &lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;datetime&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.logged_date&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;N&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;N&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[10/10/2022]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;last_updated_date&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt; &lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;datetime&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.last_updated_date&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[2022-10-10 10:04:49.0]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtraFlag11&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra Flag 11&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtraFlag11&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;N&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;N&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD applnSequenceField=&quot;Y&quot;&gt;
&lt;HTMLNAME&gt;app_seq_no&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;App Seq No&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.app_seq_no&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;N&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;N&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[P0027256]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtRegistrationNumber&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Registration Number&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtRegistrationNumber&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[BED202210353066]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtAppName&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Candidate Name&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtAppName&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[POOJA VERMA]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtFatherName&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Candidate Father Name&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtFatherName&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[SHYAM SUNDER SINGH VERMA]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtMotherName&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Candidate Mother Name&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtMotherName&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[BRIJESH KUMARI]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtEmail&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Email Address&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtEmail&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[mukeshverma0817@gmail.com]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtMobile&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Primary Mobile Number&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtMobile&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[8737042266]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtAlternateMobile&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Alternate Mobile Number&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtAlternateMobile&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[7505673242]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtGender&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Gender&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtGender&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[Female]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtSearchGender&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Gender Search&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtSearchGender&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[Female]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCategory&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Category&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCategory&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[SC]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;isPWD&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Person with Disability&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.isPWD&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[No]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtSubCategory&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Sub Category&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtSubCategory&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtStateDomicile&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;State Domicile&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtStateDomicile&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[UP]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtAnualFamilyIncome&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Annual Family Income less than 2 Lac pa&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtAnualFamilyIncome&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;isZeroFeesRequired&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Zero Fees Required&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.isZeroFeesRequired&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;isEconomicallyWeaker&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Economically Weaker&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.isEconomicallyWeaker&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;optedStream&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Stream Opted for B.ED&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.optedStream&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[Science]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtAdmitCardRollNumber&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Admit Card Roll Number&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtAdmitCardRollNumber&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[54293180]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtWrittenTestMarks&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Written Test Marks&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtWrittenTestMarks&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[145.333]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtTotalMarks&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Total Marks&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtTotalMarks&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[145.333]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtRank&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Rank&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtRank&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[116923]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtStateRank&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;State Rank&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtStateRank&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[116923]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCategoryRank&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Category Rank&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCategoryRank&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[SC  16824]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;isExserviceMan&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Ex Service Man&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.isExserviceMan&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[No]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;isGovernmentEmployee&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Government Employee&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.isGovernmentEmployee&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[No]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;isPoliceFamily&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Police Family&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.isPoliceFamily&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[No]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;isFreedomFIghter&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Freedom Fighter&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.isFreedomFIghter&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[No]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;isDefence&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Defense&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.isDefence&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[No]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtUniversityCode&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;University Code&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;text&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtUniversityCode&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[004,004,004,004,004]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCollegeCode&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;College Code&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;text&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCollegeCode&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[SK1758,AK1598,AK1601,AK1609,AK1610]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtStreamCode&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Stream Code&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;text&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtStreamCode&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[SA,SA,SA,SA,SA]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCollegePreference&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;College and Preference&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;text&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCollegePreference&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[SA,004,SK1758-@GC@-SA,004,AK1598-@GC@-SA,004,AK1601-@GC@-SA,004,AK1609-@GC@-SA,004,AK1610]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCourseChoice&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Course Choice&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCourseChoice&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[SA]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtIsSanskrit&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Sanskrit&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtIsSanskrit&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[No]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;isFinalSubmit&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Final Submit&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.isFinalSubmit&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[Yes]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtIsDuplicate&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Duplicate&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtIsDuplicate&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;appPaymentStatus&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;App Payment Status&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.appPaymentStatus&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;paymentTransactionNo&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Payment Transaction Number&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.paymentTransactionNo&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;paymentReceiptNo&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Payment Receipt Number&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.paymentReceiptNo&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;orderid&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Order Id&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.orderid&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;payment_request_time&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Payment Request Time(dd/MMM/yyyy)&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;datetime&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.payment_request_time&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;payment_response_time&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Payment Response Time(dd/MMM/yyyy)&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;datetime&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.payment_response_time&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;payment_mode&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Payment Mode&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.payment_mode&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;payment_status&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Payment Status&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.payment_status&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txt_Amount&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Total Amount&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txt_Amount&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtraFlag1&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra Flag 1&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtraFlag1&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtraFlag2&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra Flag 2&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtraFlag2&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtraFlag3&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra Flag 3&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtraFlag3&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtraFlag4&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra Flag 4&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtraFlag4&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtraFlag5&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra Flag 5&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtraFlag5&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtraFlag6&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra Flag 6&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtraFlag6&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtraFlag7&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra Flag 7&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtraFlag7&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtraFlag8&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra Flag 8&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtraFlag8&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtraFlag9&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra Flag 9&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtraFlag9&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtraFlag10&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra Flag 10&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtraFlag10&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtra1&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra 1&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtra1&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtra2&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra 2&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtra2&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtra3&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra 3&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtra3&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtra4&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra 4&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtra4&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtra5&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra 5&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtra5&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtra6&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra 6&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtra6&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtra7&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra 7&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtra7&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtra8&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra 8&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtra8&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtra9&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra 9&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtra9&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtExtra10&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Extra 10&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtExtra10&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtIsEligibleForCounselling&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Eligible For Counselling&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtIsEligibleForCounselling&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[Yes]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtRound&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Round&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtRound&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[1]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtPhase&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Phase&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtPhase&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[2]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtIsCounsellingFeePaid&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Counselling Fee Paid&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtIsCounsellingFeePaid&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtIsChoiceFilled&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Choice Filled&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtIsChoiceFilled&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtIsSeatAlotted&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Seat Allotted&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtIsSeatAlotted&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtallotmentDate&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Allotment Date&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtallotmentDate&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCollegeSeatCategory&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;College Seat Category&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCollegeSeatCategory&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtPreferenceNumber&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Preference Number&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtPreferenceNumber&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtIsDecisionTaken&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Decision Taken&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtIsDecisionTaken&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtActionTaken&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Action Taken&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtActionTaken&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtIsWithdrawn&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Withdrawn&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtIsWithdrawn&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtIsDirectAdmission&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Is Direct Admission&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtIsDirectAdmission&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R1_txtIsCounsellingFeePaid&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R1 Is Counselling Fee paid&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R1_txtIsCounsellingFeePaid&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[Yes]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R1_txtIsChoiceFilled&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R1 Is Choice Filled&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R1_txtIsChoiceFilled&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R1_txtIsSeatAlotted&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R1 Is Seat Allotted&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R1_txtIsSeatAlotted&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R1_txtallotmentDate&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R1 Allotment Date&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R1_txtallotmentDate&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R1_txtUniversityCode&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R1 University Code&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R1_txtUniversityCode&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R1_txtCollegeCode&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R1 College Code&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R1_txtCollegeCode&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R1_txtStreamCode&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R1 Stream Code&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R1_txtStreamCode&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R1_txtCollegeSeatCategory&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R1 College Seat Category&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R1_txtCollegeSeatCategory&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R1_txtPreferenceNumber&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R1 Preference Number&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R1_txtPreferenceNumber&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R1_txtIsDecisionTaken&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R1 Is Decision Taken&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R1_txtIsDecisionTaken&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R1_txtActionTaken&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R1 Action Taken&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R1_txtActionTaken&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R1_txtIsWithdrawn&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R1 Is Withdrawn&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R1_txtIsWithdrawn&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R2_txtIsCounsellingFeePaid&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R2 Is Counselling Fee paid&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R2_txtIsCounsellingFeePaid&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R2_txtIsChoiceFilled&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R2 Is Choice Filled&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R2_txtIsChoiceFilled&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R2_txtIsSeatAlotted&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R2 Is Seat Allotted&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R2_txtIsSeatAlotted&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R2_txtallotmentDate&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R2 Allotment Date&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R2_txtallotmentDate&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R2_txtUniversityCode&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R2 University Code&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R2_txtUniversityCode&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R2_txtCollegeCode&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R2 College Code&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R2_txtCollegeCode&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R2_txtStreamCode&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R2 Stream Code&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R2_txtStreamCode&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R2_txtCollegeSeatCategory&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R2 College Seat Category&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R2_txtCollegeSeatCategory&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R2_txtPreferenceNumber&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R2 Preference Number&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R2_txtPreferenceNumber&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R2_txtIsDecisionTaken&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R2 Is Decision Taken&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R2_txtIsDecisionTaken&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R2_txtActionTaken&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R2 Action Taken&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R2_txtActionTaken&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R2_txtIsWithdrawn&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R2 Is Withdrawn&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R2_txtIsWithdrawn&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R3_txtIsCounsellingFeePaid&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R3 Is Counselling Fee paid&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R3_txtIsCounsellingFeePaid&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R3_txtIsChoiceFilled&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R3 Is Choice Filled&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R3_txtIsChoiceFilled&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R3_txtIsSeatAlotted&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R3 Is Seat Allotted&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R3_txtIsSeatAlotted&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R3_txtallotmentDate&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R3 Allotment Date&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R3_txtallotmentDate&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R3_txtUniversityCode&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R3 University Code&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R3_txtUniversityCode&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R3_txtCollegeCode&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R3 College Code&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R3_txtCollegeCode&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R3_txtStreamCode&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R3 Stream Code&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R3_txtStreamCode&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R3_txtCollegeSeatCategory&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R3 College Seat Category&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R3_txtCollegeSeatCategory&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R3_txtPreferenceNumber&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R3 Preference Number&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R3_txtPreferenceNumber&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R3_txtIsDecisionTaken&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R3 Is Decision Taken&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R3_txtIsDecisionTaken&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R3_txtActionTaken&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R3 Action Taken&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R3_txtActionTaken&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;R3_txtIsWithdrawn&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;R3 Is Withdrawn&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.R3_txtIsWithdrawn&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCounsellingExtra1&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Counselling Extra 1&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCounsellingExtra1&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[2]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCounsellingExtra2&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Counselling Extra 2&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCounsellingExtra2&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCounsellingExtra3&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Counselling Extra 3&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCounsellingExtra3&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCounsellingExtra4&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Counselling Extra 4&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCounsellingExtra4&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCounsellingExtra5&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Counselling Extra 5&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCounsellingExtra5&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[5000]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCounsellingExtra6&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Counselling Extra 6&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCounsellingExtra6&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCounsellingExtra7&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Counselling Extra 7&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCounsellingExtra7&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCounsellingExtra8&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Counselling Extra 8&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCounsellingExtra8&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCounsellingExtra9&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Counselling Extra 9&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCounsellingExtra9&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;FIELD&gt;
&lt;HTMLNAME&gt;txtCounsellingExtra10&lt;/HTMLNAME&gt;
&lt;HTMLDISPLAYNAME&gt;Counselling Extra 10&lt;/HTMLDISPLAYNAME&gt;
&lt;DATATYPE&gt;varchar&lt;/DATATYPE&gt;
&lt;QUERYNAME&gt;app.txtCounsellingExtra10&lt;/QUERYNAME&gt;
&lt;UPDATABLE_APPLICANT&gt;Y&lt;/UPDATABLE_APPLICANT&gt;
&lt;UPDATABLE_ADMIN&gt;Y&lt;/UPDATABLE_ADMIN&gt;
&lt;VALUE&gt;&amp;lt;![CDATA[]]&amp;gt;&lt;/VALUE&gt;
&lt;/FIELD&gt;
&lt;/RESPONSE&gt;
" id="strDisplayProfile">
	<input type="hidden" name="siteMasterFieldName" value="" id="siteMasterFieldName"> 
	<input type="hidden" name="entityId" value="" id="entityId"> 
	<input type="hidden" name="adminFlag" id="adminFlag" value="null" /> 
	<input type="hidden" name="isPreview" id="isPreview" value="" /> 
	<input type="hidden" name="txtCourses" id="txtCourses" value="" /> 
	<input type="hidden" name="checksum" id="checksum" value="" />
	<input type="hidden" name="loginField" id="loginField" value=""; />
	<input type="hidden" name="token_img" id="token_img" value="" />
	
	<input type="hidden" name="sessChk" id="sessChk" value="1665375811834" />  
	<input type="hidden" name="copyrightYear" id="copyrightYear" value="2022" />  
	<input type="hidden" name="txtFileName" id="txtFileName" value="" />
<input type="hidden" name="txtFilePath" id="txtFilePath" value="" />
<input type="hidden" id="txtFilePathEdit" name="txtFilePathEdit"/>
<input type="hidden" id="txtFileNameEdit" name="txtFileNameEdit"/>
<input type="hidden" name="txtFileDisplayName" id="txtFileDisplayName" value="" />	
		  <input type="hidden" name="app_seq_no" id="app_seq_no" value="" /> 
		<input type="hidden" name=applnSequenceField id="applnSequenceField" value="app_seq_no" />  <script>document.getElementById("siteMasterFieldName").value=''</script>


	<link rel="icon" href="images/onlineAppForm/form64585/Univ Logo.png">
<link href="css/onlineApplicationForm/jquery.tabs.css" rel="stylesheet" type="text/css">
<link href="css/onlineApplicationForm/tab.css" rel="stylesheet" type="text/css">
<meta charset="utf-8">
<meta content="minimum-scale=1.0, width=device-width, maximum-scale=1, user-scalable=no" name="viewport" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta http-equiv="X-UA-Compatible" content="IE=Edge">
<style>
	blink {color:white; -webkit-animation: blink 3s step-end infinite; animation: blink 1s step-end infinite}
	@-webkit-keyframes blink {67% { opacity: 0 }}
	@keyframes blink{67% { opacity: 0 }}
</style>

<div class="listbannerarea customBannerDivClass" id="bannerDiv1"></div>

<div id="container-11" style="background: #fff;">
	<ul class="nav nav-pills  responsive-tabs tabs-nav" id="tabs" style="margin-bottom: -5px;">
		<li role="presentation" style="width: 14.2857%; min-width: 30px; max-width: 190px; !important" class="active" >
		<a href="#fragment-28"  data-attr="#fragment-28" role="tab" data-toggle="tab">
			<div class="Absolute-Center clearfix" style="padding-left:8px;">
				<div class="tabicon">
					<i class="applicationprofile"></i>
				</div>
				<div class="tabtext sansSB" style="display: inline;">
					<span>College Selection</span>
				</div>
			</div>
		</a>
		</li>
   </ul>

	<div>
		<div class="tabs-container" style="padding: 0px 0px; position: relative;width:100%; border:0;">
		 	<div class="container" style="margin-top: 0px;width:100%; padding:0px; background-color:#ffffff">
				<section class="container-fluid mainSection">
					<div class="customTabContainerDiv" id="">
						<div class="tab-insidecontent customSectionDivClass newTabHeading" id="section_1_heading_div">
							<span id="PersonalDetails_span">Personal Details</span>
						</div>
						<div class="tab-insidecontent" style="margin-top: -1px;">
							<div class="row rowTopMargin" >
		                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 marginTop alignRightClass">
		                            <label id="" class="view-label-bold">Registration Number</label>
		               			</div>
		                        <div style="word-break:break-all" id="txtRegistrationNumber_div" class="col-lg-3 col-md-3 col-sm-3 col-xs-12 marginTop">NA</div>
		                        <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 marginTop alignRightClass">
		                            <label id="" class="view-label-bold">Candidate Name</label>
		                        </div>
		                        <div style="word-break:break-all" id="txtAppName_div" class="col-lg-3 col-md-3 col-sm-3 col-xs-12 marginTop">NA</div>
			     			</div>
                     		<div class="row rowTopMargin">
                     			<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 marginTop alignRightClass">
                            		<label id="" class="view-label-bold">Email Id</label>
                         		</div>
                        		<div style="word-break:break-all" id="txtEmail_div" class="col-lg-3 col-md-3 col-sm-3 col-xs-12 marginTop">NA</div>
								<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 marginTop alignRightClass">
                            		<label id="" class="view-label-bold">Mobile Number</label>
                         		</div>
                        		<div style="word-break:break-all" id="txtMobile_div" class="col-lg-3 col-md-3 col-sm-3 col-xs-12 marginTop">NA</div>
							</div>
							<div class="row rowTopMargin">
								<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 marginTop alignRightClass">
                            		<label id="" class="view-label-bold">Alternate Mobile Number</label>
                         		</div>
                        		<div style="word-break:break-all" id="txtAlternateMobile_div" class="col-lg-3 col-md-3 col-sm-3 col-xs-12 marginTop">NA</div>
							</div>
						</div>
					</div>
					
        			<div class="customTabContainerDiv1" id="">
						<div class="tab-insidecontent customSectionDivClass newTabHeading" id="">
							<span id="SelectedPreference_span">Selected College</span>
						</div>
						<div class="" id="finalPreferenceTableView" style="border: 1px solid #ddd;margin: 0px 15px ;">
							<table id="no-more-tables" class="table removemarginbottom postdatatable table-striped">
								<thead class="theadColor">
									<tr>
										<th><label id="">Preference</label></th>
										<th><label id="">University Code</label></th>
										<th><label id="">University Name</label></th>
										<th><label id="">College Code</label></th>
										<th><label id="">College Name</label></th>
										<th id="stream_preview"><label id="">Course</label></th>
										<th><label id="">Type of College</label></th>
										<th><label id="">College Category</label></th>
									</tr>
								</thead>
								<tbody id="selectedCollegeListView"></tbody>
							</table>
						</div>
       				</div>
        
        			<div class="customTabContainerDiv" id="">
						<div class="tab-insidecontent customSectionDivClass newTabHeading" id="">
							<span id="">Declaration</span>
						</div>
						<div class="tab-insidecontent customSectionDivClass" id="sectionData_Declaration_13" style="margin-top: -1px;">
							<div class="row">
								<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 inheritHeight">
									<table>
										<tbody>
											<tr>
												<td>
													<p style="margin-bottom: 0;">
														I will accept the college/institute allotted to me on the basis of my state rank and choices submitted in U.P. B.Ed. J.E.E-2022 entrance examination.
													</p>
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>	
					
					<div class="btndiv customClassForBtnDiv width100" style="margin-left:0px !important;" id="submit_div" align="center">
						<div class="" >
							<a onclick="fnEditApplication();" class="check" id="edit_button" data-toggle="tooltip" title="Edit Preferences" style="display:none;">Edit Preferences</a>
							<a onclick="createPrintData();" class="check" id="print_button" data-toggle="tooltip" title="Print">Print</a>
							<a onclick="closeViewPage()" class="check" id="close_button" data-toggle="tooltip" title="Close">Close</a>
						</div>
					</div>
				</section>
			</div>
		</div> 
	</div>
</div>

<div id="loader" class="loaderDivClass" style=""><img class="loaderImgClass" src="images/onlineAppForm/loader.gif"></div>

<div align="center" id="alertMsgPopulateDiv" class="pop" style="display: none;">
 	<div style="display: block;height: 30%;" id="myPop2"></div>
	<div style="overflow: auto;height: 219px;border: 5px solid lightgray;border-radius: 10px;width: 325px;" class="pop-content">
		<div class="" id="alertMsgPopulate" style="overflow: auto;text-align: center;padding:30px 5px 0px 5px;height: 155px;background-color: white;font-size: 14px;"></div>
		<div class="pop-footer" id="" style="">
			<button type="button" class="btn btn-info Ok_button" onclick="$('#alertMsgPopulateDiv').fadeOut(100);">OK</button> 
		</div>
	</div>
	<div style="display: block;" id="myPop3"></div>
</div>

<span style="display:none" id="txtGender_div"></span>
<span style="display:none" id="txtSearchGender_div"></span>
<span style="display:none" id="txtCategory_div"></span>
<span style="display:none" id="isPWD_div"></span>
<span style="display:none" id="txtDisabilityType_div"></span>
<span style="display:none" id="isBlind_div"></span>
<span style="display:none" id="txtStateDomicile_div"></span>
<span style="display:none" id="txtSubCategory_div"></span>
<span style="display:none" id="txtIsExserviceman_div"></span>
<span style="display:none" id="txtIsFreedomFighter_div"></span>
<span style="display:none" id="txtRank_div"></span>
<span style="display:none" id="txtRollNumber_div"></span>
<span style="display:none" id="optedStream_div"></span>
<span style="display:none" id="txtIsSanskrit_div"></span>
<span style="display:none" id="txtStreamCode_div"></span>
<span style="display:none" id="txtUniversityCode_div"></span>
<span style="display:none" id="txtCollegeCode_div"></span>
<span style="display:none" id="txtCollegePreference_div"></span>
<span style="display:none" id="txtCourseChoice_div"></span>
<span style="display:none" id="isFinalSubmit_div"></span>
<span style="display:none" id="txtIsDuplicate_div"></span>
<span style="display:none" id="txtIsEligibleForCounselling_div"></span>
<span style="display:none" id="txtRound_div"></span>
<span style="display:none" id="txtPhase_div"></span>
<span style="display:none" id="txtIsCounsellingFeePaid_div"></span>
<span style="display:none" id="txtIsChoiceFilled_div"></span>
<span style="display:none" id="txtIsSeatAlotted_div"></span>
<span style="display:none" id="txtallotmentDate_div"></span>
<span style="display:none" id="txtCollegeSeatCategory_div"></span>
<span style="display:none" id="txtPreferenceNumber_div"></span>
<span style="display:none" id="txtIsDecisionTaken_div"></span>
<span style="display:none" id="txtActionTaken_div"></span>
<span style="display:none" id="txtIsWithdrawn_div"></span>
<span style="display:none" id="txtIsDirectAdmission_div"></span>
<span style="display:none" id="R1_txtIsCounsellingFeePaid_div"></span>
<span style="display:none" id="R1_txtIsChoiceFilled_div"></span>
<span style="display:none" id="R1_txtIsSeatAlotted_div"></span>
<span style="display:none" id="R1_txtallotmentDate_div"></span>
<span style="display:none" id="R1_txtUniversityCode_div"></span>
<span style="display:none" id="R1_txtCollegeCode_div"></span>
<span style="display:none" id="R1_txtStreamCode_div"></span>
<span style="display:none" id="R1_txtCollegeSeatCategory_div"></span>
<span style="display:none" id="R1_txtPreferenceNumber_div"></span>
<span style="display:none" id="R1_txtIsDecisionTaken_div"></span>
<span style="display:none" id="R1_txtActionTaken_div"></span>
<span style="display:none" id="R1_txtIsWithdrawn_div"></span>
<span style="display:none" id="R2_txtIsCounsellingFeePaid_div"></span>
<span style="display:none" id="R2_txtIsChoiceFilled_div"></span>
<span style="display:none" id="R2_txtIsSeatAlotted_div"></span>
<span style="display:none" id="R2_txtallotmentDate_div"></span>
<span style="display:none" id="R2_txtUniversityCode_div"></span>
<span style="display:none" id="R2_txtCollegeCode_div"></span>
<span style="display:none" id="R2_txtStreamCode_div"></span>
<span style="display:none" id="R2_txtCollegeSeatCategory_div"></span>
<span style="display:none" id="R2_txtPreferenceNumber_div"></span>
<span style="display:none" id="R2_txtIsDecisionTaken_div"></span>
<span style="display:none" id="R2_txtActionTaken_div"></span>
<span style="display:none" id="R2_txtIsWithdrawn_div"></span>
<span style="display:none" id="R3_txtIsCounsellingFeePaid_div"></span>
<span style="display:none" id="R3_txtIsChoiceFilled_div"></span>
<span style="display:none" id="R3_txtIsSeatAlotted_div"></span>
<span style="display:none" id="R3_txtallotmentDate_div"></span>
<span style="display:none" id="R3_txtUniversityCode_div"></span>
<span style="display:none" id="R3_txtCollegeCode_div"></span>
<span style="display:none" id="R3_txtStreamCode_div"></span>
<span style="display:none" id="R3_txtCollegeSeatCategory_div"></span>
<span style="display:none" id="R3_txtPreferenceNumber_div"></span>
<span style="display:none" id="R3_txtIsDecisionTaken_div"></span>
<span style="display:none" id="R3_txtActionTaken_div"></span>
<span style="display:none" id="R3_txtIsWithdrawn_div"></span>
<span style="display:none" id="txtCounsellingExtra1_div"></span>
<span style="display:none" id="txtCounsellingExtra2_div"></span>
<span style="display:none" id="txtCounsellingExtra3_div"></span>
<span style="display:none" id="txtCounsellingExtra4_div"></span>
<span style="display:none" id="txtCounsellingExtra5_div"></span>
<span style="display:none" id="txtCounsellingExtra6_div"></span>
<span style="display:none" id="txtCounsellingExtra7_div"></span>
<span style="display:none" id="txtCounsellingExtra8_div"></span>
<span style="display:none" id="txtCounsellingExtra9_div"></span>
<span style="display:none" id="txtCounsellingExtra10_div"></span>
<span style="display:none" id="txtExtraFlag1_div"></span>
<span style="display:none" id="txtExtraFlag2_div"></span>
<span style="display:none" id="txtExtraFlag3_div"></span>
<span style="display:none" id="txtExtraFlag4_div"></span>
<span style="display:none" id="txtExtraFlag5_div"></span>
<span style="display:none" id="txtExtra1_div"></span>
<span style="display:none" id="txtExtra2_div"></span>
<span style="display:none" id="txtExtra3_div"></span>
<span style="display:none" id="txtExtra4_div"></span>
<span style="display:none" id="txtExtra5_div"></span>
<span style="display:none" id="txtFatherName_div"></span>
<span style="display:none" id="txtMotherName_div"></span>
<span style="display:none" id="txtAppDOB_div"></span>
<span style="display:none" id="txtMobileNo_div"></span>
<span style="display:none" id="txtStateRank_div"></span>
<span style="display:none" id="txtCategoryRank_div"></span>
<span style="display:none" id="txtTotalMarks_div"></span>
<span style="display:none" id="txtWrittenTestMarks_div"></span>
<span style="display:none" id="txtTotalWeightage_div"></span>
<span style="display:none" id="txtRegistrationType_div"></span>
<span style="display:none" id="ExtraDate1_div"></span>
<span style="display:none" id="ExtraDate2_div"></span>
<span style="display:none" id="ExtraDate3_div"></span>
<span style="display:none" id="ExtraDate4_div"></span>
<span style="display:none" id="ExtraDate5_div"></span>
<span style="display:none" id="ExtraInt1_div"></span>
<span style="display:none" id="ExtraInt2_div"></span>
<span style="display:none" id="ExtraInt3_div"></span>
<span style="display:none" id="ExtraInt4_div"></span>
<span style="display:none" id="ExtraInt5_div"></span>
<span style="display:none" id="txtExtra6_div"></span>
<span style="display:none" id="R1_txtRegistrationType_div"></span>
<span style="display:none" id="R2_txtRegistrationType_div"></span>
<span style="display:none" id="R3_txtRegistrationType_div"></span>
<span style="display:none" id="txtCounsellingStream_div"></span> 

	

	
  <input type="hidden" name="viewOnloadMethod" value="getViewDetails(1936,76621)" id="viewOnloadMethod">
 <input type="hidden" name="viewFormHtmlPath" value="/html/form76621/applicationView.html" id="viewFormHtmlPath">
	<input type="hidden" name="orgId" value="1936" id="orgId"> 
	<input type="hidden" name="formId" value="76621" id="formId"> 
	<input type="hidden" name="userID" value="P0027256" id="userID">
	<input type="hidden" name="tabLayout" value="horizontalWithIcon" id="tabLayout">
	
	<input name="isFormMultilingualRequired" id="isFormMultilingualRequired" type="hidden" value="N" />
	<input name="consent_required" id="consent_required" type="hidden" value="N" />
	<input name="consent_agreed" id="consent_agreed" type="hidden" value="" />
	<input name="data_deletion" id="data_deletion" type="hidden" value="N" />
	<input name="slotBkngTabId" id="slotBkngTabId" type="hidden" value="0" />
	<input name="hallTcktTabId" id="hallTcktTabId" type="hidden" value="0" />
	<input name="qpPblishTabId" id="qpPblishTabId" type="hidden" value="0" />
	<input name="currentFragmentId" id="currentFragmentId" type="hidden" value="" />
	<input value="" id="wherefilters" name="wherefilters" type="hidden">
	  
 <input type="hidden" name="imgChkSum" id="imgChkSum" value="TKzaSklYkV9L6o7b41LMOOPAySOYXtGqSXwlvRs1x8U%3D"/>
 <script>
			   
				if(document.getElementById("adminFlag").value != null && document.getElementById("adminFlag").value == 'Y')
				{
					if(document.getElementById("edit_div") != null && document.getElementById("edit_div") != undefined )
					document.getElementById("edit_div").style.display = "none";
					
					if($("#print_div")!=null && $("#print_div")!=undefined && ($("#print_div > a").attr("onclick") == "javascript:window.print()" || $("#print_div > a").attr("onclick") == "window.print()")){
						$("#print_div > a").attr("onclick","printFWWindow()");
					}
					if(document.getElementById("formId").value=="34")
					{
					
					
					document.getElementById("administrator").style.display="block";
					document.getElementById("applicantReceived").style.display="none";
					document.getElementById("applicantNotReceived").style.display="none";
					}
					
					
				}
				else if(document.getElementById("adminFlag").value != null && document.getElementById("adminFlag").value == 'N' && document.getElementById("isPreview").value != null && document.getElementById("isPreview").value == 'Y')
				{
					if(document.getElementById("edit_div") != null && document.getElementById("edit_div") != undefined )
					document.getElementById("edit_div").style.display = "none";
					if(document.getElementById("logout_div") != null && document.getElementById("logout_div") != undefined )
					document.getElementById("logout_div").style.display = "none";
					if($("#print_div")!=null && $("#print_div")!=undefined && ($("#print_div > a").attr("onclick") == "javascript:window.print()" || $("#print_div > a").attr("onclick") == "window.print()")){
						$("#print_div > a").attr("onclick","printFWWindow()");
					}
					if(document.getElementById("formId").value=="34")
					{
					
					
					document.getElementById("administrator").style.display="block";
					document.getElementById("applicantReceived").style.display="none";
					document.getElementById("applicantNotReceived").style.display="none";
					}
					
					
				}
				else
				{
				
				if(document.getElementById("formId").value=="34")
				{
				
				  if(false==true){
				
					document.getElementById("administrator").style.display="block";
					document.getElementById("applicantReceived").style.display="block";
					document.getElementById("editAdministrator").style.display="block";
					document.getElementById("applicantNotReceived").style.display="none";
					} else if(false==false){
					
					document.getElementById("administrator").style.display="none";
					document.getElementById("applicantReceived").style.display="none";
					document.getElementById("applicantNotReceived").style.display="block";
					
					} 
				 
				 
				 
				 }
				
		       }
		       			
		</script> 
		<input type="hidden" name="editField" id="editField" value="Y" />
		 
		<input type="hidden" id="testCenterReferral" name="testCenterReferral" value="" /> <input
		type="hidden" id="hdnSubject" name="hdnSubject" value="" /> 
		<input type="hidden" id="hdnTestDate" name="hdnTestDate" value="" />
	<div>
	<div id="footerHolder">
	<table width="100%" border="0" cellspacing="0" cellpadding="0">
		<tr>
			<td align="center" class="hinttext">Version 14.04.01</td>
		</tr>
	</table>
	</div>
	</div>
	</div>

	<div id="popupContact" class="popupContact" style="display: none">
	<a id="popupContactClose" style="cursor: pointer;">x</a>
	<div id="popup">
	<table width="400" height="160" class="blue">
		<tbody>
			<tr height="7px"></tr>
			<tr align="center" height="30px">
				<td id='applicant_name_qb' colspan='2'></td>
			</tr>
			<tr height="30px">
				<td align="right"><span class="mandatory">*</span>Name:</td>
				<td><input type="text" maxlength="30" name="qpName" id="qpName"
					class="text_field_required"></td>
			</tr>
			<tr>
				<td align="right"><span class="mandatory">*</span>Password:</td>
				<td><input type="password" maxlength="10" name="password"
					id="password" class="text_field_required" autocomplete="off"></td>
			</tr>
			<tr align="center" height="15px">
				<td align="center" colspan='2'>
				<div><font color="red" id="divMessage"
					style="font-family: Arial; font-size: 18px;"></font></div>
				</td>
			</tr>
			<tr align="center" height="30px">
				<td align="center" id="button_qb_div" colspan='2'>
				<input type="button" style="cursor: pointer; background: url(images/onlineAppForm/submit.gif) no-repeat; border: none; height: 28px; width: 75px;" onclick="genarateQP('2563');" id="Submit" class="nexttabbutton" value="">
				<input type="button" style="cursor: pointer; background: url(images/onlineAppForm/cancel_new.gif) no-repeat; border: none; height: 28px; width: 75px;" onclick="disablePopup();" id="Cancel" class="nexttabbutton" value="">
					</td>
			</tr>
			<tr align="center" height="30px">
				<td align="center" colspan='2'>Please enter a Name and Password
				for Question Paper before proceeding. You will require this password
				to authenticate the downloading of Question Paper.</td>
			</tr>
			<tr>
				<td colspan='2' align="center">To view Password policy <a
					onclick="showPwdPolicy();" href="#">click</a> here.</td>
			</tr>
			<tr>
				<td colspan='2'>&nbsp;</td>
			</tr>
			<tr id="pwd_policy" style="display: none">
				<td colspan='2'><b>Password Policy:</b> Password should contain
				minimum 6 and maximum 10 characters. It should have atleast one
				numeric digit, one upper case letter, one lower case letter and one
				special character among these: @!#$^*_+:</td>
			</tr>
			<tr id="okBtn_pwd" style="display: none">
				<td align="center" colspan='2'><a onclick="hidePwdPolicy();"
					href="#">OK</a></td>
			</tr>
		</tbody>
	</table>
	</div>
	</div>
	<div id="popupChangePassword" class="popupChangePassword"
		style="display: none"><a id="popupChangePasswordClose"
		style="cursor: pointer;">x</a>
	<div id="popupChangePwd">
	<table width="400" height="160" class="blue">
		<tbody>
			<tr height="7px"></tr>
			<tr align="center" height="30px">
				<td id='applicant_name_chngPwd' colspan='2'></td>
			</tr>
			<tr height="30px">
				<td align="right"><span class="mandatory">*</span>User Id:</td>
				<td><input type="text" maxlength="30" name="userid" id="userid"
					class="text_field_required"></td>
			</tr>
			<tr>
				<td align="right"><span class="mandatory">*</span>Password:</td>
				<td><input type="password" maxlength="10" name="confData"
					id="confData" class="text_field_required"></td>
			</tr>
			<tr align="center" height="30px">
				<td align="center" id="button_CP_div" colspan='2'><input
					type="button" onclick="fnNormalChangePassword()"
					style="background: #C2E3F4;" value="Change Password" name="button2"></td>
			</tr>
			<tr align="center" height="30px">
				<td align="center" colspan='2'>Please enter your User Id and
				Password before proceeding.</td>
			</tr>
		</tbody>
	</table>
	</div>
	</div>

					<input type="hidden" id="eicuListing" name="eicuListing" value="true" />
	
	<div class="overlayBG" style="display: none;"></div>
	<div style="display: none;" id="popupGrid">

	<div class="popup_div">
	<div class="portlet_topper">
	<div class="popupheader" id="popuptitle">Popup Title</div>
	<div class="arrowplace"><a class="remove_popup" href="#nogo"
		onclick="fnCloseGridPopup()">Close</a></div>
	</div>

	<div style="border-top: 1px solid #8BABC2; height: 1px; width: 100%;overflow-x:auto;"></div>
	<div class="popup_content"><iframe width="100%" height="100%"
		style="border: 0;" id="frame1" src=""> </iframe></div>


	</div>
	</div>
	<div id="backgroundPopup" class="backgroundPopup"></div>
	<div id="loader_div" style="display: none;" align="center">
	<table width="250px" height="200px"
		style="position: absolute; top: 120px; left: 470px;">
		<tbody>
			<tr>
				<td><a href="#"><img width="50px" height="50px"
					src="images/onlineAppForm/loader.gif"></a></td>
			</tr>
		</tbody>
	</table>
	</div>
</form>

<div id="hallTicketPopUp" class="modal fade hallTicketPopUp" role="dialog">
   
</div>
<div id="hallTicketPopUpLBA" class="modal fade hallTicketPopUpLBA _lba" role="dialog">
   
</div>
<div id="confirmPop" class="modal fade msgPop confirmPop" role="dialog" style="display: none;">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header b_g_c_white">
        <button type="button" class="close" data-dismiss="modal" data-tooltip="tooltip" title="" data-original-title="Close">
        <div class="close_link">
			<svg xml:space="preserve" enable-background="new 0 0 24 24" viewBox="0 0 24 24" height="24px" width="24px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1">
			<path d="M20.203,20.475c-0.241,0.227-0.62,0.215-0.847-0.027l-7.082-7.708
				l-7.112,7.706c-0.227,0.244-0.605,0.256-0.847,0.027c-0.241-0.229-0.253-0.611-0.027-0.857l7.161-7.758L4.463,4.372
				C4.237,4.131,4.249,3.751,4.49,3.525c0.242-0.227,0.621-0.214,0.847,0.027l6.928,7.422l6.883-7.417
				c0.226-0.244,0.604-0.256,0.847-0.027c0.241,0.229,0.253,0.612,0.027,0.856l-6.933,7.471l7.141,7.77
				C20.456,19.869,20.444,20.248,20.203,20.475z" class="close_icon" fill="#333333" clip-rule="evenodd" fill-rule="evenodd"></path>
			</svg></div>
		</button>
        <div class="icoCont">
        	<div class="ico"><i class="fa fa-check" aria-hidden="true"></i></div>
        </div>
      </div>
      <div class="modal-body">
        <div class="confHdTxt">Slot Booked Successfully</div>
        <div class="confTxt">Close popup to see more details.</div>
      </div>
      <div class="modal-footer b_g_c_white">
         <button type="button"   class="btn btn-default contiBtn" data-dismiss="modal" onclick="$('#hallTicketPopUp').modal('hide')">OK</button>
      </div>
    </div>

  </div>
</div>

<div id="confirmClose" class="modal fade msgPop confirmClose" role="dialog" style="display: none;">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header b_g_c_white">
        <button type="button" class="close" data-dismiss="modal" data-tooltip="tooltip" title="" data-original-title="Close">
        <div class="close_link">
			<svg xml:space="preserve" enable-background="new 0 0 24 24" viewBox="0 0 24 24" height="24px" width="24px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1">
			<path d="M20.203,20.475c-0.241,0.227-0.62,0.215-0.847-0.027l-7.082-7.708
				l-7.112,7.706c-0.227,0.244-0.605,0.256-0.847,0.027c-0.241-0.229-0.253-0.611-0.027-0.857l7.161-7.758L4.463,4.372
				C4.237,4.131,4.249,3.751,4.49,3.525c0.242-0.227,0.621-0.214,0.847,0.027l6.928,7.422l6.883-7.417
				c0.226-0.244,0.604-0.256,0.847-0.027c0.241,0.229,0.253,0.612,0.027,0.856l-6.933,7.471l7.141,7.77
				C20.456,19.869,20.444,20.248,20.203,20.475z" class="close_icon" fill="#333333" clip-rule="evenodd" fill-rule="evenodd"></path>
			</svg></div>
		</button>
        <div class="icoCont">
        	<div class="ico"><i class="fa fa-times" aria-hidden="true"></i></div>
        </div>
      </div>
      <div class="modal-body">
        <div class="confHdTxt">Slot Could Not Be Booked</div>
        <div class="confTxt"> </div>
      </div>
      <div class="modal-footer b_g_c_white">
         <button type="button"   class="btn btn-default contiBtn" data-dismiss="modal" onclick="$('#hallTicketPopUp').modal('hide')">OK</button>
      </div>
    </div>

  </div>
</div>

<div id="confirmPopLBA" class="modal fade msgPop confirmPop _lba" role="dialog" style="display: none;">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" data-tooltip="tooltip" title="Close" data-original-title="Close">
        <div class="close_link">
			<svg xml:space="preserve" enable-background="new 0 0 24 24" viewBox="0 0 24 24" height="24px" width="24px" y="0px" x="0px" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns="http://www.w3.org/2000/svg" id="Layer_1" version="1.1">
			<path d="M20.203,20.475c-0.241,0.227-0.62,0.215-0.847-0.027l-7.082-7.708
				l-7.112,7.706c-0.227,0.244-0.605,0.256-0.847,0.027c-0.241-0.229-0.253-0.611-0.027-0.857l7.161-7.758L4.463,4.372
				C4.237,4.131,4.249,3.751,4.49,3.525c0.242-0.227,0.621-0.214,0.847,0.027l6.928,7.422l6.883-7.417
				c0.226-0.244,0.604-0.256,0.847-0.027c0.241,0.229,0.253,0.612,0.027,0.856l-6.933,7.471l7.141,7.77
				C20.456,19.869,20.444,20.248,20.203,20.475z" class="close_icon" fill="#333333" clip-rule="evenodd" fill-rule="evenodd"></path>
			</svg></div>
		</button>
        <div class="icoCont">
        	<div class="ico"><i class="fa fa-check" aria-hidden="true"></i></div>
        </div>
      </div>
      <div class="modal-body">
        <div class="confHdTxt">Slot Booked Successfully</div>
      </div>
      <div class="modal-footer">
         <button type="button"   class="btn btn-default contiBtn" data-dismiss="modal" onclick="$('#hallTicketPopUp').modal('hide')">OK</button>
      </div>
    </div>

  </div>
</div>



 <div id="pop_body">
    </div>
</div>
<div id="pop_bodyNew" style="display:none">
<div class="modal fade uploadimagepop" tabindex="-1" role="dialog">
  <div class="modal-dialog upload-modal">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close" data-toggle="tooltip" title="Close" ><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" data-staticKey="Document / Image Upload">Document / Image Upload</h4>
      </div>
      <div class="modal-body clearfix">
      <div class="mainblueSubtab clearfix hidden-xs hidden-sm">
      <ul role="tablist" class="list-inline pull-left " id="tabsUL">
      </ul>
      </div>
      <div class="visible-sm visible-xs clearfix" id="UploadDropdownForMobileOuterDiv"  >
        <div class="tabledropdown pull-right col-sm-4 col-xs-12 padding0"> <div class="form-group" id="tabsDropdownForMobile">
                </div></div>
           </div>
        
					
      
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


    </div>
	
	 <div role='dialog' id='captureImageForUpload' class='modal captureImageForUpload fade addNew in' style='z-index: 10050;'>
  <div class='modal-dialog'>
    
<div class='modal-content' style='width: fit-content;/* right: -250px; */ float: right;right: 25%;'>
    
        <div class='modal-header' style='background-color: #f6f6f6 !important;'>
            
                     <button type='button' class='close' data-dismiss='modal' aria-label='Close' data-toggle='tooltip' title='Close' onclick='javascript:stopvideo("upload");' style='color:black;top: 0px;margin-top: 10px;width: 25px;height: 19px;opacity: 0.8;'><span aria-hidden='true' style=''>×</span></button>
            <div style='text-align: center;padding-bottom: 10px;padding-top: 10px;color: #23b7e5;font-size: 18px;'>Please hit the click button below to capture your photo</div>
        </div>
      
        <div class='modal-body modal-body-default' style='min-height: 100px;'>
            <div style='' class='captureImageSection '>
                
                <div class='videoStream_Upload' id='videoStream_Upload' style='padding-top: 10px;'>
                    <div id='video-container_Upload' style='padding: 10px;background: white;-webkit-box-shadow: 0 1px 10px #D9D9D9;-moz-box-shadow: 0 1px 10px #D9D9D9;-ms-box-shadow: 0 1px 10px #D9D9D9;-o-box-shadow: 0 1px 10px #D9D9D9;box-shadow: 0 1px 10px #D9D9D9;'>
 
                        <video id='camera-stream_Upload' onclick='snapshot(this);' autoplay='' style='padding-left: 0px;padding-right: 0px;max-height: 450px;' width='100%' class=''></video>
                        <video id='camera-streamR_Upload' class='hide' autoplay='' style='padding-left: 0px;padding-right: 0px; max-height: 420px;' width='100%'></video>
                        <canvas id='myCanvas_Upload' class='hide' style='padding-left: 0px;padding-right: 0px;' width='650px' height='500px'></canvas>
                    </div>
                
                </div>
            </div>  
      </div>
      <div class='modal-footer loginopt modal-footer-default' style='background-color: #f6f6f6;margin-left: 0px;margin-top: 0px;padding-top: 5px;padding-bottom: 10px;'>
        <div class='captureImgButton_Upload' id='captureImgButton_Upload' style='text-align: center;'>
            


<a style='cursor:pointer' class='crop_btn' onclick='javascript:captureImg();' data-statickey='Click'>Click</a>
                     
        </div> 
      </div>
    </div>
</div>
</div>

 

 
 
 <div id='alertPop' class='modal fade msgPop alertPop' role='dialog'>
			  <div class='modal-dialog'>
				
				<div class='modal-content' style="/* left: 380px; */ width: fit-content;float: right;right: 35%;">
				  <div class='modal-header'>
					<button type='button' class='close' data-dismiss='modal' data-toggle='tooltip' title='' data-original-title='Close'></button>
					<div class='ico'> ALERT ! ! !</div>
				  </div>
				  <div class='modal-body'>
					<div class='confTxt'></div>
				  </div>
				  <div class='modal-footer'>
					<div class='aligncenterbtn'>
					  <button style='' type='button' class='btn btn-default contiBtn' id='modalConfirm' data-dismiss='modal'>Ok</button>
					 </div>
				  </div>
				</div>
			  </div>                                                                                               
		</div>

<input id="cropList" type="hidden" value="" name="cropList">
<input id="imgMandChk" type="hidden" value="" name="imgMandChk">
<input id="imageUploadInViewPage" type="hidden" value="Y" name="imageUploadInViewPage">
</body>
</html>